import {
  Zap, Users, FileText, Globe, Mail, Target,
  BarChart3, Database, Sparkles, Search, Image,
  FolderOpen, Send, TrendingUp, Eye, Play,
  Mic, Type, Clipboard, Activity, Bot, Brain,
  Workflow, Filter, Timer, ShieldCheck, Bell,
  LayoutDashboard, Split, Repeat, FileSearch,
  MessageSquare, Gauge, Lock, Cpu, Layers, Settings,
  Webhook,
  // Extended palette icons (from AI Automation source)
  Calendar, Clock, Heart, Languages, Scan, Wrench,
  BookOpen, FileOutput, GitBranch, GitMerge, Scale,
  ShieldAlert, Bookmark, CopyCheck, Package, Smartphone,
  FileType2, ImagePlus, Video, Shuffle, Code, FileJson,
  // Additional icons used across the platform
  AlertTriangle, UserCheck, GitFork, BrainCircuit,
  ArrowRight, Grid3X3, Square, DollarSign, CheckCircle2,
  XCircle, AlertCircle, CircleDot, Boxes, SlidersHorizontal,
  History, Variable, Code2, Pin, PinOff,
  Repeat2, Link2, Paperclip, Bold, Italic,
  StickyNote, Download, Copy, Scissors,
  Undo2, Redo2, Magnet, HelpCircle, X,
  ChevronDown, ChevronLeft, ChevronRight, ChevronUp,
  Maximize2, Minimize2, ZoomIn, ZoomOut, Crosshair,
  MousePointer, Check, Loader2, Plus, Trash2, Save,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

const ICONS: Record<string, LucideIcon> = {
  // ── Core node icons ─────────────────────────────────────────────────────
  'zap': Zap,
  'users': Users,
  'file-text': FileText,
  'globe': Globe,
  'mail': Mail,
  'target': Target,
  'bar-chart': BarChart3,
  'database': Database,
  'sparkles': Sparkles,
  'search': Search,
  'image': Image,
  'folder-open': FolderOpen,
  'send': Send,
  'trending-up': TrendingUp,
  'eye': Eye,
  'play': Play,
  'mic': Mic,
  'type': Type,
  'clipboard': Clipboard,
  'activity': Activity,
  'bot': Bot,
  'brain': Brain,
  'workflow': Workflow,
  'filter': Filter,
  'timer': Timer,
  'shield-check': ShieldCheck,
  'bell': Bell,
  'layout-dashboard': LayoutDashboard,
  'webhook': Webhook,
  'split': Split,
  'repeat': Repeat,
  'file-search': FileSearch,
  'message-square': MessageSquare,
  'gauge': Gauge,
  'lock': Lock,
  'cpu': Cpu,
  'layers': Layers,
  'settings': Settings,

  // ── Extended palette icons ──────────────────────────────────────────────
  'calendar': Calendar,
  'clock': Clock,
  'heart': Heart,
  'languages': Languages,
  'scan': Scan,
  'wrench': Wrench,
  'book-open': BookOpen,
  'file-output': FileOutput,
  'git-branch': GitBranch,
  'git-merge': GitMerge,
  'scale': Scale,
  'shield-alert': ShieldAlert,
  'bookmark': Bookmark,
  'copy-check': CopyCheck,
  'package': Package,
  'smartphone': Smartphone,
  'file-type-2': FileType2,
  'image-plus': ImagePlus,
  'video': Video,
  'shuffle': Shuffle,
  'code': Code,
  'file-json': FileJson,

  // ── Advanced flow icons ─────────────────────────────────────────────────
  'alert-triangle': AlertTriangle,
  'user-check': UserCheck,
  'git-fork': GitFork,
  'brain-circuit': BrainCircuit,
  'arrow-right': ArrowRight,
  'grid-3x3': Grid3X3,
  'square': Square,
  'dollar-sign': DollarSign,
  'check-circle-2': CheckCircle2,
  'x-circle': XCircle,
  'alert-circle': AlertCircle,
  'circle-dot': CircleDot,
  'boxes': Boxes,
  'sliders-horizontal': SlidersHorizontal,
  'history': History,
  'variable': Variable,
  'code-2': Code2,
  'pin': Pin,
  'pin-off': PinOff,
  'repeat-2': Repeat2,
  'link-2': Link2,
  'paperclip': Paperclip,
  'bold': Bold,
  'italic': Italic,
  'sticky-note': StickyNote,
  'download': Download,
  'copy': Copy,
  'scissors': Scissors,
  'undo-2': Undo2,
  'redo-2': Redo2,
  'magnet': Magnet,
  'help-circle': HelpCircle,
  'x': X,

  // ── Navigation / UI icons ──────────────────────────────────────────────
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'maximize-2': Maximize2,
  'minimize-2': Minimize2,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
  'crosshair': Crosshair,
  'mouse-pointer': MousePointer,
  'check': Check,
  'loader-2': Loader2,
  'plus': Plus,
  'trash-2': Trash2,
  'save': Save,
}

/**
 * Returns a Lucide icon component for a given icon key.
 * Falls back to Zap for unknown keys.
 * Logo icons (logo-openai, etc.) return null -- those are handled by ToolLogos.
 */
export function getNodeIcon(iconKey: string): LucideIcon | null {
  if (iconKey.startsWith('logo-')) return null
  return ICONS[iconKey] ?? Zap
}

export function getAllIconEntries(): [string, LucideIcon][] {
  return Object.entries(ICONS)
}
