import type { AutomationSystem, WorkflowTemplate } from './types'

/**
 * Grid position helper — accounts for largest node sizes (subsystem: 320×130).
 *
 * x = 40 + column * 380  (320px max width + 60px gap)
 * y: 40 + row    * 160  (130px max height + 30px gap)
 */
const p = (col: number, row: number) => ({
  x: 40 + col * 380,
  y: 40 + row * 160,
})

// ── Demo Automation Systems ────────────────────────────────────────────────

export const DEMO_SYSTEMS: AutomationSystem[] = [
  // ── 0. Recruiting Agentur (Master with Sub-Systems) ─────────────────────
  {
    id: 'demo-recruiting',
    user_id: 'local-user',
    isDemo: true,
    name: 'Recruiting Agentur',
    description: 'Vollständiger Agentur-Fulfillment-Prozess: Vom gewonnenen Client über Onboarding, Knowledge Processing und Content-Produktion bis zum Launch mit Performance-Tracking.',
    category: 'Recruiting',
    icon: 'building-2',
    status: 'active',
    webhookUrl: '',
    nodes: [
      { id: 'rm1', label: 'Client gewonnen', description: 'Vertrag unterschrieben – Übergabe von Sales', icon: 'trophy', type: 'trigger', x: 60, y: 200 },
      { id: 'rm2', label: 'Handover-Formular', description: 'Internes Formular mit allen Client-Daten', icon: 'clipboard-check', type: 'trigger', x: 60, y: 370 },
      { id: 'rm3', label: 'Daten zusammenführen', description: 'Sales-Daten & Formular validieren und mergen', icon: 'git-merge', type: 'process', x: 340, y: 270 },
    ],
    connections: [
      { from: 'rm1', to: 'rm3' },
      { from: 'rm2', to: 'rm3' },
      { from: 'rm3', to: 'sub-demo-recruiting-kickoff' },
      { from: 'sub-demo-recruiting-kickoff', to: 'sub-demo-recruiting-onboarding' },
      { from: 'sub-demo-recruiting-onboarding', to: 'sub-demo-recruiting-knowledge' },
      { from: 'sub-demo-recruiting-knowledge', to: 'sub-demo-recruiting-content' },
      { from: 'sub-demo-recruiting-content', to: 'sub-demo-recruiting-review' },
      { from: 'sub-demo-recruiting-review', to: 'sub-demo-recruiting-tracking' },
    ],
    groups: [],
    outputs: [
      { id: 'o1', name: 'Abschlussbericht – TechStart GmbH', type: 'document', link: '#', createdAt: '2026-02-20T16:00:00Z' },
    ],
    lastExecuted: '2026-02-20T16:00:00Z',
    executionCount: 8,
  },

  // ── 0a. Kickoff & Client Setup (Sub-System) ───────────────────────────────
  {
    id: 'demo-recruiting-kickoff',
    user_id: 'local-user',
    isDemo: true,
    parentId: 'demo-recruiting',
    subSystemOrder: 0,
    name: 'Kickoff & Client Setup',
    description: 'Internes Setup: CRM-Eintrag, Kommunikation, Projekt-Board, Ordnerstruktur und Arbeitsdokumente.',
    category: 'Recruiting',
    icon: 'clipboard-check',
    status: 'active',
    webhookUrl: '',
    nodes: [
      { id: 'ks1', label: 'Handover-Formular', description: 'Internes Übergabeformular ausgefüllt', icon: 'logo-typeform', type: 'trigger', x: 40, y: 198 },
      { id: 'ks2', label: 'CRM-Eintrag', description: 'Client-Profil, Pipeline & Tags anlegen', icon: 'logo-hubspot', type: 'process', x: 380, y: 198 },
      { id: 'ks3', label: 'Interner Slack-Kanal', description: 'Dedizierter Team-Kanal für den Kunden', icon: 'logo-slack', type: 'output', x: 720, y: 18 },
      { id: 'ks4', label: 'Willkommens-Mail', description: 'Automatische Begrüßungs-Sequenz an Client', icon: 'logo-gmail', type: 'output', x: 720, y: 178 },
      { id: 'ks5', label: 'Onboarding-Anleitung', description: 'Vorbereitungsinstruktionen an Client senden', icon: 'logo-gmail', type: 'output', x: 720, y: 338 },
      { id: 'ks6', label: 'Kick-off Termin', description: 'Onboarding-Call im Kalender erstellen', icon: 'logo-google-calendar', type: 'output', x: 720, y: 498 },
      { id: 'ks7', label: 'Projekt-Board', description: 'Client-Projekt mit Standard-Aufgaben anlegen', icon: 'logo-notion', type: 'process', x: 1060, y: 178 },
      { id: 'ks8', label: 'Aufgaben generieren', description: 'Onboarding, Review, Go-Live Checklisten', icon: 'list-checks', type: 'process', x: 1400, y: 178 },
      { id: 'ks9', label: 'Ordnerstruktur', description: 'Assets, Copy, Tracking, Reports, Website', icon: 'logo-google-drive', type: 'output', x: 1060, y: 498 },
      { id: 'ks10', label: 'Arbeitsdokumente', description: 'Templates duplizieren & personalisieren', icon: 'logo-google-docs', type: 'output', x: 1400, y: 498 },
      { id: 'ks11', label: 'Status: Onboarding', description: 'CRM-Status auf "Onboarding läuft" setzen', icon: 'logo-hubspot', type: 'process', x: 1740, y: 198 },
    ],
    connections: [
      { from: 'ks1', to: 'ks2' },
      { from: 'ks2', to: 'ks3' }, { from: 'ks2', to: 'ks4' }, { from: 'ks2', to: 'ks5' }, { from: 'ks2', to: 'ks6' },
      { from: 'ks2', to: 'ks7' }, { from: 'ks7', to: 'ks8' },
      { from: 'ks2', to: 'ks9' }, { from: 'ks9', to: 'ks10' },
      { from: 'ks8', to: 'ks11' }, { from: 'ks10', to: 'ks11' },
    ],
    groups: [
      { id: 'gks1', label: 'Eingang', x: 15, y: 138, width: 620, height: 148, color: 'blue' },
      { id: 'gks2', label: 'Kommunikation', x: 695, y: 0, width: 280, height: 560, color: 'blue' },
      { id: 'gks3', label: 'Projekt & Dateien', x: 1035, y: 118, width: 620, height: 450, color: 'purple' },
      { id: 'gks4', label: 'Abschluss', x: 1715, y: 138, width: 280, height: 148, color: 'green' },
    ],
    outputs: [],
    executionCount: 0,
  },

  // ── 0b. Client Onboarding (Sub-System) ─────────────────────────────────────
  {
    id: 'demo-recruiting-onboarding',
    user_id: 'local-user',
    isDemo: true,
    parentId: 'demo-recruiting',
    subSystemOrder: 1,
    name: 'Client Onboarding',
    description: 'Material-Sammlung, Onboarding-Gespräch und KI-Transkription — der strategische Input für das gesamte System.',
    category: 'Recruiting',
    icon: 'users',
    status: 'active',
    webhookUrl: '',
    nodes: [
      { id: 'ob1', label: 'Upload-Anleitung', description: 'Client erhält Anweisungen für Material-Upload', icon: 'logo-gmail', type: 'output', x: 40, y: 198 },
      { id: 'ob2', label: 'Material-Upload', description: 'Client lädt Bilder, Texte, Brand Assets hoch', icon: 'upload', type: 'process', x: 380, y: 198 },
      { id: 'ob3', label: 'Material-Ordner', description: 'Alle Materialien zentral organisiert', icon: 'logo-google-drive', type: 'output', x: 380, y: 338 },
      { id: 'ob4', label: 'Onboarding Call', description: 'Standardisiertes Gespräch nach Fragebogen', icon: 'video', type: 'process', x: 720, y: 198 },
      { id: 'ob5', label: 'KI-Transkription', description: 'Call aufnehmen, transkribieren und analysieren', icon: 'logo-openai', type: 'ai', x: 1060, y: 198 },
      { id: 'ob6', label: 'Transkript gespeichert', description: 'Maschinenlesbares Wissen dauerhaft gesichert', icon: 'logo-google-docs', type: 'output', x: 1400, y: 118 },
      { id: 'ob7', label: 'Slack: Call abgeschlossen', description: 'Team über erfolgreichen Call informieren', icon: 'logo-slack', type: 'output', x: 1400, y: 338 },
    ],
    connections: [
      { from: 'ob1', to: 'ob2' },
      { from: 'ob2', to: 'ob3' },
      { from: 'ob2', to: 'ob4' },
      { from: 'ob4', to: 'ob5' },
      { from: 'ob5', to: 'ob6' },
      { from: 'ob5', to: 'ob7' },
    ],
    groups: [
      { id: 'gob1', label: 'Material-Sammlung', x: 15, y: 138, width: 620, height: 280, color: 'blue' },
      { id: 'gob2', label: 'Onboarding Call', x: 695, y: 138, width: 620, height: 148, color: 'purple' },
      { id: 'gob3', label: 'Ergebnis', x: 1375, y: 58, width: 280, height: 368, color: 'green' },
    ],
    outputs: [],
    executionCount: 0,
  },

  // ── 0c. Knowledge Processing (Sub-System) ──────────────────────────────────
  {
    id: 'demo-recruiting-knowledge',
    user_id: 'local-user',
    isDemo: true,
    parentId: 'demo-recruiting',
    subSystemOrder: 2,
    name: 'Knowledge Processing',
    description: 'Transkript analysieren, Zielgruppen-Avatar, Anbieter-Profil und Core Messaging als strategische Basis-Dokumente erstellen.',
    category: 'Recruiting',
    icon: 'sparkles',
    status: 'active',
    webhookUrl: '',
    nodes: [
      { id: 'kp1', label: 'Transkript-Analyse', description: 'KI analysiert und strukturiert das Transkript', icon: 'logo-openai', type: 'ai', x: 40, y: 198 },
      { id: 'kp2', label: 'Daten extrahieren', description: 'Pain Points, Benefits, Sprachmuster extrahieren', icon: 'logo-claude', type: 'ai', x: 380, y: 198 },
      { id: 'kp3', label: 'Zielgruppen-Avatar', description: 'Detailliertes Profil der Zielgruppe', icon: 'logo-google-docs', type: 'output', x: 720, y: 118 },
      { id: 'kp4', label: 'Anbieter-Avatar', description: 'Marken- und Anbieter-Steckbrief', icon: 'logo-google-docs', type: 'output', x: 720, y: 198 },
      { id: 'kp5', label: 'Core Messaging', description: 'Kern-Botschaften und Positionierung', icon: 'logo-google-docs', type: 'output', x: 720, y: 278 },
      { id: 'kp6', label: 'Zusammenführen', description: 'Alle Dokumente als Single Source of Truth', icon: 'git-merge', type: 'process', x: 1060, y: 198 },
      { id: 'kp7', label: 'Qualitätsprüfung', description: 'Manuelle Faktenprüfung (Human Review)', icon: 'shield-check', type: 'process', x: 1400, y: 198 },
      { id: 'kp8', label: 'Slack: Basis fertig', description: 'Team über fertige Strategie-Basis informieren', icon: 'logo-slack', type: 'output', x: 1740, y: 198 },
    ],
    connections: [
      { from: 'kp1', to: 'kp2' },
      { from: 'kp2', to: 'kp3' }, { from: 'kp2', to: 'kp4' }, { from: 'kp2', to: 'kp5' },
      { from: 'kp3', to: 'kp6' }, { from: 'kp4', to: 'kp6' }, { from: 'kp5', to: 'kp6' },
      { from: 'kp6', to: 'kp7' },
      { from: 'kp7', to: 'kp8' },
    ],
    groups: [
      { id: 'gkp1', label: 'KI-Analyse', x: 15, y: 138, width: 620, height: 148, color: 'purple' },
      { id: 'gkp2', label: 'Strategische Dokumente', x: 695, y: 58, width: 280, height: 308, color: 'purple' },
      { id: 'gkp3', label: 'Qualitätssicherung', x: 1035, y: 138, width: 960, height: 148, color: 'green' },
    ],
    outputs: [],
    executionCount: 0,
  },

  // ── 0d. Content & Asset Production (Sub-System) ────────────────────────────
  {
    id: 'demo-recruiting-content',
    user_id: 'local-user',
    isDemo: true,
    parentId: 'demo-recruiting',
    subSystemOrder: 3,
    name: 'Content & Asset Production',
    description: 'Marketing-Copy generieren, Website bauen, Bilder vorbereiten und alles veröffentlichen.',
    category: 'Recruiting',
    icon: 'file-text',
    status: 'active',
    webhookUrl: '',
    nodes: [
      { id: 'cp1', label: 'KI: Website-Texte', description: 'Website & Landing Page Copy generieren', icon: 'logo-claude', type: 'ai', x: 40, y: 18 },
      { id: 'cp2', label: 'KI: Ad Copy', description: 'Meta, Google & weitere Anzeigentexte', icon: 'logo-claude', type: 'ai', x: 40, y: 198 },
      { id: 'cp3', label: 'Template auswählen', description: 'Passendes Website-Template selektieren', icon: 'layout', type: 'process', x: 380, y: 118 },
      { id: 'cp4', label: 'Copy einsetzen', description: 'Generierte Texte in Template einsetzen', icon: 'text-cursor-input', type: 'process', x: 720, y: 118 },
      { id: 'cp5', label: 'Bilder vorbereiten', description: 'Client-Bilder oder KI-generierte Bilder', icon: 'image', type: 'process', x: 720, y: 198 },
      { id: 'cp6', label: 'Design anpassen', description: 'Farben, Stil & Layout finalisieren', icon: 'palette', type: 'process', x: 1060, y: 118 },
      { id: 'cp7', label: 'Website bauen', description: 'Alle Elemente zusammenfügen', icon: 'logo-wordpress', type: 'process', x: 1400, y: 118 },
      { id: 'cp8', label: 'Domain verbinden', description: 'Domain konfigurieren & SSL', icon: 'globe', type: 'process', x: 1740, y: 118 },
      { id: 'cp9', label: 'Website Live', description: 'Seite veröffentlichen', icon: 'globe', type: 'output', x: 2080, y: 18 },
      { id: 'cp10', label: 'Copy-Dokumente', description: 'Alle generierten Texte gespeichert', icon: 'logo-google-docs', type: 'output', x: 2080, y: 198 },
    ],
    connections: [
      { from: 'cp1', to: 'cp3' }, { from: 'cp1', to: 'cp4' },
      { from: 'cp2', to: 'cp4' }, { from: 'cp2', to: 'cp10' },
      { from: 'cp3', to: 'cp4' },
      { from: 'cp4', to: 'cp6' }, { from: 'cp5', to: 'cp6' },
      { from: 'cp6', to: 'cp7' },
      { from: 'cp7', to: 'cp8' },
      { from: 'cp8', to: 'cp9' },
    ],
    groups: [
      { id: 'gcp1', label: 'KI-Generierung', x: 15, y: 0, width: 280, height: 280, color: 'purple' },
      { id: 'gcp2', label: 'Website-Erstellung', x: 355, y: 58, width: 1580, height: 228, color: 'blue' },
      { id: 'gcp3', label: 'Ergebnis', x: 2055, y: 0, width: 280, height: 280, color: 'green' },
    ],
    outputs: [],
    executionCount: 0,
  },

  // ── 0e. Review & Launch (Sub-System) ───────────────────────────────────────
  {
    id: 'demo-recruiting-review',
    user_id: 'local-user',
    isDemo: true,
    parentId: 'demo-recruiting',
    subSystemOrder: 4,
    name: 'Review & Launch',
    description: 'Kampagnen vorbereiten, interne Reviews durchführen, finale Freigabe und Zusammenfassung erstellen.',
    category: 'Recruiting',
    icon: 'shield-check',
    status: 'active',
    webhookUrl: '',
    nodes: [
      { id: 'rl1', label: 'Kampagnen-Struktur', description: 'Targeting, Budgets & Anzeigengruppen', icon: 'logo-google-ads', type: 'process', x: 40, y: 118 },
      { id: 'rl2', label: 'Ad-Creatives', description: 'Anzeigen mit Copy, Media & URLs vorbereiten', icon: 'logo-meta', type: 'process', x: 380, y: 118 },
      { id: 'rl3', label: 'Interne Benachrichtigung', description: 'Team erhält Übersicht aller fertigen Assets', icon: 'logo-slack', type: 'output', x: 720, y: 118 },
      { id: 'rl4', label: 'Review-Aufgaben', description: 'Checklisten-basierte Prüfaufgaben erstellen', icon: 'list-checks', type: 'process', x: 1060, y: 118 },
      { id: 'rl5', label: 'Copy-Check', description: 'Texte auf Korrektheit & Tonalität prüfen', icon: 'spell-check', type: 'process', x: 1400, y: 18 },
      { id: 'rl6', label: 'Seiten-Check', description: 'Website & Landing Pages verifizieren', icon: 'monitor-check', type: 'process', x: 1400, y: 118 },
      { id: 'rl7', label: 'Tracking-Check', description: 'Analytics & Conversion-Tracking prüfen', icon: 'chart-bar', type: 'process', x: 1400, y: 218 },
      { id: 'rl8', label: 'Finale Freigabe', description: 'Manuelle Endabnahme (Human Review)', icon: 'shield-check', type: 'process', x: 1740, y: 118 },
      { id: 'rl9', label: 'KI: Zusammenfassung', description: 'Abschluss-PDF mit Zielgruppe, Links & Status', icon: 'logo-claude', type: 'ai', x: 2080, y: 118 },
      { id: 'rl10', label: 'Projekt → Live', description: 'Transition zu laufendem Betrieb', icon: 'rocket', type: 'output', x: 2420, y: 118 },
    ],
    connections: [
      { from: 'rl1', to: 'rl2' },
      { from: 'rl2', to: 'rl3' },
      { from: 'rl3', to: 'rl4' },
      { from: 'rl4', to: 'rl5' }, { from: 'rl4', to: 'rl6' }, { from: 'rl4', to: 'rl7' },
      { from: 'rl5', to: 'rl8' }, { from: 'rl6', to: 'rl8' }, { from: 'rl7', to: 'rl8' },
      { from: 'rl8', to: 'rl9' },
      { from: 'rl9', to: 'rl10' },
    ],
    groups: [
      { id: 'grl1', label: 'Kampagnen-Vorbereitung', x: 15, y: 58, width: 960, height: 148, color: 'blue' },
      { id: 'grl2', label: 'Parallele Reviews', x: 1035, y: 0, width: 620, height: 288, color: 'orange' },
      { id: 'grl3', label: 'Freigabe & Launch', x: 1715, y: 58, width: 960, height: 148, color: 'green' },
    ],
    outputs: [],
    executionCount: 0,
  },

  // ── 0f. Performance Tracking (Sub-System) ──────────────────────────────────
  {
    id: 'demo-recruiting-tracking',
    user_id: 'local-user',
    isDemo: true,
    parentId: 'demo-recruiting',
    subSystemOrder: 5,
    name: 'Performance Tracking',
    description: 'Tägliche Performance-Daten sammeln, KPIs analysieren, Reports erstellen und KI-basierte Optimierungsvorschläge.',
    category: 'Recruiting',
    icon: 'bar-chart',
    status: 'active',
    webhookUrl: '',
    nodes: [
      { id: 'pt1', label: 'Zeitplan (täglich)', description: 'Täglicher/periodischer Daten-Refresh', icon: 'calendar', type: 'trigger', x: 40, y: 118 },
      { id: 'pt2', label: 'Ad-Daten abrufen', description: 'Performance-Daten von Meta, Google & Co.', icon: 'logo-google-ads', type: 'process', x: 380, y: 118 },
      { id: 'pt3', label: 'KI: KPI-Analyse', description: 'KPIs berechnen, Trends erkennen', icon: 'logo-openai', type: 'ai', x: 720, y: 118 },
      { id: 'pt4', label: 'Tracking-Sheet', description: 'Impressions, Clicks, CTR, CPC, Leads', icon: 'logo-google-sheets', type: 'output', x: 1060, y: 18 },
      { id: 'pt5', label: 'Dashboard Update', description: 'Live-Dashboard für Team & Client', icon: 'logo-google-sheets', type: 'output', x: 1060, y: 118 },
      { id: 'pt6', label: 'Slack: Daily Report', description: 'Täglichen Performance-Report posten', icon: 'logo-slack', type: 'output', x: 1060, y: 218 },
      { id: 'pt7', label: 'KI-Optimierung', description: 'Automatische Kampagnen-Anpassungsvorschläge', icon: 'logo-claude', type: 'ai', x: 1400, y: 118 },
    ],
    connections: [
      { from: 'pt1', to: 'pt2' },
      { from: 'pt2', to: 'pt3' },
      { from: 'pt3', to: 'pt4' }, { from: 'pt3', to: 'pt5' }, { from: 'pt3', to: 'pt6' },
      { from: 'pt3', to: 'pt7' },
    ],
    groups: [
      { id: 'gpt1', label: 'Datenerfassung', x: 15, y: 58, width: 620, height: 148, color: 'blue' },
      { id: 'gpt2', label: 'Analyse & Reporting', x: 695, y: 0, width: 960, height: 308, color: 'purple' },
    ],
    outputs: [],
    executionCount: 0,
  },

  // ── 1. Marketing Agency Fulfillment (Full Workflow) ──────────────────────
  {
    id: 'demo-1',
    user_id: 'local-user',
    isDemo: true,
    name: 'Marketing Agency Fulfillment',
    description:
      'End-to-End Agentur-Workflow: Vom Typeform-Eingang über KI-Analyse, parallele Produktion (Website, Ads, Content) bis zum Go-Live — mit Quality Gates, Routing und Error Handling.',
    category: 'Operations',
    icon: 'workflow',
    status: 'active',
    webhookUrl: '',
    nodes: [
      // ── Phase 0: Client Intake ──────────────────────────────────────────
      { id: 'm01', label: 'Typeform Eingang', description: 'Neuer Kunde füllt Onboarding-Formular aus', icon: 'logo-typeform', type: 'trigger', x: 60, y: 300 },
      { id: 'm02', label: 'Slack: Neuer Kunde', description: 'Team wird über neuen Kunden informiert', icon: 'logo-slack', type: 'output', x: 360, y: 160 },
      { id: 'm03', label: 'Sheet: Tracking', description: 'Projekt-Zeile im Master-Sheet angelegt', icon: 'logo-google-sheets', type: 'process', x: 360, y: 440 },

      // ── Phase 1: Onboarding & Analyse ───────────────────────────────────
      { id: 'm04', label: 'Kickoff-Call abwarten', description: '48h auf Calendly-Buchung warten', icon: 'clock', type: 'wait', x: 660, y: 300 },
      { id: 'm05', label: 'KI-Transkription', description: 'Call wird transkribiert und aufbereitet', icon: 'logo-openai', type: 'ai', x: 940, y: 300 },
      { id: 'm06', label: 'Strategie-Agent', description: 'Extrahiert Zielgruppe, USPs, Positionierung, Budget', icon: 'brain', type: 'agent', x: 1220, y: 300 },

      // ── Phase 2: Quality Gate ───────────────────────────────────────────
      { id: 'm07', label: 'Manager-Freigabe', description: 'Account Manager prüft den Strategie-Brief', icon: 'shield-check', type: 'approval', x: 1500, y: 300 },
      { id: 'm08', label: 'Brief vollständig?', description: 'Prüft ob alle Pflichtfelder gefüllt sind', icon: 'git-branch', type: 'ifelse', x: 1780, y: 300 },
      { id: 'm09', label: 'Feedback-Loop', description: 'Brief unvollständig — zurück an Account Manager', icon: 'alert-triangle', type: 'error-handler', x: 1780, y: 560 },

      // ── Phase 3: Produktion (Fork → 3 Branches) ────────────────────────
      { id: 'm10', label: 'Produktion starten', description: 'Website, Ads & Content laufen parallel', icon: 'git-fork', type: 'fork', x: 2100, y: 300 },

      // Branch A — Website
      { id: 'm11', label: 'Page Structure', description: 'Sections, Conversion-Flow, CTA-Platzierung', icon: 'layout-dashboard', type: 'process', x: 2420, y: 80 },
      { id: 'm12', label: 'Page Copy', description: 'Headlines, Body, Testimonials generieren', icon: 'logo-claude', type: 'ai', x: 2700, y: 80 },
      { id: 'm13', label: 'Code Generator', description: 'HTML / CSS / JS aus Struktur + Copy erzeugen', icon: 'code', type: 'process', x: 2980, y: 80 },
      { id: 'm14', label: 'Deploy Website', description: 'Landing Page live auf Vercel deployen', icon: 'globe', type: 'output', x: 3260, y: 80 },

      // Branch B — Ads
      { id: 'm15', label: 'Kampagnen-Struktur', description: 'Campaigns, Ad Sets, Targeting definieren', icon: 'target', type: 'process', x: 2420, y: 300 },
      { id: 'm16', label: 'Ad Copy Generator', description: 'Headlines, Primary Texts, Hook-Varianten', icon: 'logo-openai', type: 'ai', x: 2700, y: 300 },
      { id: 'm17', label: 'Creative Variants', description: '3-5 Varianten pro Ad Set generieren', icon: 'logo-claude', type: 'ai', x: 2980, y: 300 },

      // Branch C — Content & SEO
      { id: 'm18', label: 'SEO Research', description: 'Keywords, Suchvolumen, Wettbewerb analysieren', icon: 'scan', type: 'ai', x: 2420, y: 520 },
      { id: 'm19', label: 'Blog & Artikel', description: 'SEO-optimierte Artikel und Pillar Pages', icon: 'logo-claude', type: 'ai', x: 2700, y: 520 },
      { id: 'm20', label: 'Social Posts', description: 'Posts für Meta, LinkedIn, Instagram', icon: 'logo-meta', type: 'output', x: 2980, y: 520 },

      // ── Phase 4: Kanal-Distribution ─────────────────────────────────────
      { id: 'm21', label: 'Pipeline Sync', description: 'Alle 3 Branches abgeschlossen', icon: 'git-merge', type: 'join', x: 3540, y: 300 },
      { id: 'm22', label: 'Kanal-Router', description: 'Verteilt Creatives an die richtigen Plattformen', icon: 'shuffle', type: 'router', x: 3820, y: 300 },
      { id: 'm23', label: 'Google Ads', description: 'Kampagne in Google Ads hochladen', icon: 'logo-google-ads', type: 'output', x: 4100, y: 120 },
      { id: 'm24', label: 'Meta Ads', description: 'Kampagne in Meta Business Suite erstellen', icon: 'logo-meta', type: 'output', x: 4100, y: 300 },
      { id: 'm25', label: 'LinkedIn Ads', description: 'B2B-Kampagne in LinkedIn Campaign Manager', icon: 'logo-linkedin', type: 'output', x: 4100, y: 480 },

      // ── Phase 5: QA & Tracking ──────────────────────────────────────────
      { id: 'm26', label: 'Channels zusammen', description: 'Alle Ad-Plattformen bestätigt', icon: 'git-merge', type: 'merge', x: 4380, y: 300 },
      { id: 'm27', label: 'Analytics Setup', description: 'GA4, Pixel, Conversion Tracking einrichten', icon: 'logo-google-analytics', type: 'process', x: 4660, y: 180 },
      { id: 'm28', label: 'QA-Check', description: 'Finale Qualitätsprüfung vor Go-Live', icon: 'shield-check', type: 'approval', x: 4660, y: 420 },

      // ── Phase 6: Go Live ────────────────────────────────────────────────
      { id: 'm29', label: 'Launch-Entscheidung', description: 'Alles freigegeben?', icon: 'git-branch', type: 'ifelse', x: 4960, y: 300 },
      { id: 'm30', label: 'Channels aktivieren', description: 'Alle Kampagnen und Seiten live schalten', icon: 'repeat', type: 'iterator', x: 5240, y: 180 },
      { id: 'm31', label: 'QA Failed', description: 'Zurück an Produktion — Fehler beheben', icon: 'alert-triangle', type: 'error-handler', x: 5240, y: 520 },
      { id: 'm32', label: 'Slack: Wir sind live!', description: 'Team und Kunde werden benachrichtigt', icon: 'logo-slack', type: 'output', x: 5520, y: 80 },
      { id: 'm33', label: 'Sheet: Final Status', description: 'Alle Links, KPIs und Status dokumentiert', icon: 'logo-google-sheets', type: 'process', x: 5520, y: 240 },
      { id: 'm34', label: 'Welcome Email', description: 'Zugangsdaten, Links und Timeline an Kunden', icon: 'logo-gmail', type: 'output', x: 5520, y: 400 },
    ],
    connections: [
      // Phase 0 → Notifications + Phase 1
      { from: 'm01', to: 'm02' },
      { from: 'm01', to: 'm03' },
      { from: 'm01', to: 'm04' },
      // Phase 1: Onboarding
      { from: 'm04', to: 'm05' },
      { from: 'm05', to: 'm06' },
      // Phase 2: Quality Gate
      { from: 'm06', to: 'm07' },
      { from: 'm07', to: 'm08' },
      { from: 'm08', to: 'm10', label: 'Vollständig' },
      { from: 'm08', to: 'm09', label: 'Unvollständig' },
      // Phase 3: Fork → 3 Branches
      { from: 'm10', to: 'm11', label: 'Website' },
      { from: 'm10', to: 'm15', label: 'Ads' },
      { from: 'm10', to: 'm18', label: 'Content' },
      // Branch A: Website
      { from: 'm11', to: 'm12' },
      { from: 'm12', to: 'm13' },
      { from: 'm13', to: 'm14' },
      // Branch B: Ads
      { from: 'm15', to: 'm16' },
      { from: 'm16', to: 'm17' },
      // Branch C: Content
      { from: 'm18', to: 'm19' },
      { from: 'm19', to: 'm20' },
      // Phase 4: Join → Router → Channels
      { from: 'm14', to: 'm21' },
      { from: 'm17', to: 'm21' },
      { from: 'm20', to: 'm21' },
      { from: 'm21', to: 'm22' },
      { from: 'm22', to: 'm23', label: 'Google' },
      { from: 'm22', to: 'm24', label: 'Meta' },
      { from: 'm22', to: 'm25', label: 'LinkedIn' },
      // Phase 5: Merge → QA
      { from: 'm23', to: 'm26' },
      { from: 'm24', to: 'm26' },
      { from: 'm25', to: 'm26' },
      { from: 'm26', to: 'm27' },
      { from: 'm26', to: 'm28' },
      // Phase 6: Launch
      { from: 'm27', to: 'm29' },
      { from: 'm28', to: 'm29' },
      { from: 'm29', to: 'm30', label: 'Go Live' },
      { from: 'm29', to: 'm31', label: 'Zurück' },
      { from: 'm30', to: 'm32' },
      { from: 'm30', to: 'm33' },
      { from: 'm30', to: 'm34' },
    ],
    groups: [
      { id: 'g-intake', label: 'Phase 0 — Client Intake', x: 25, y: 110, width: 510, height: 430, color: 'blue' },
      { id: 'g-onboarding', label: 'Phase 1 — Onboarding & Analyse', x: 625, y: 240, width: 730, height: 180, color: 'purple' },
      { id: 'g-quality', label: 'Phase 2 — Quality Gate', x: 1465, y: 240, width: 450, height: 420, color: 'orange' },
      { id: 'g-production', label: 'Phase 3 — Produktion', x: 2065, y: 20, width: 1330, height: 610, color: 'green' },
      { id: 'g-distribution', label: 'Phase 4 — Kanal-Distribution', x: 3505, y: 60, width: 730, height: 520, color: 'pink' },
      { id: 'g-qa', label: 'Phase 5 — QA & Tracking', x: 4345, y: 120, width: 450, height: 400, color: 'yellow' },
      { id: 'g-launch', label: 'Phase 6 — Go Live', x: 4925, y: 20, width: 730, height: 600, color: 'blue' },
    ],
    stickyNotes: [
      { id: 'sn1', text: '3 Produktions-Branches laufen parallel: Website, Ads & Content', x: 2200, y: 630, width: 360, height: 50, color: 'green', fontSize: 12 },
      { id: 'sn2', text: 'Router verteilt Creatives an die richtigen Ad-Plattformen', x: 3700, y: 590, width: 340, height: 50, color: 'pink', fontSize: 12 },
      { id: 'sn3', text: 'Erst nach QA-Freigabe wird gelauncht — sonst Feedback-Loop', x: 4800, y: 630, width: 360, height: 50, color: 'orange', fontSize: 12 },
      { id: 'sn4', text: 'Quality Gate: Manager muss Brief freigeben bevor Produktion startet', x: 1465, y: 670, width: 370, height: 50, color: 'orange', fontSize: 12 },
    ],
    outputs: [
      { id: 'o1', name: 'Strategie-Brief — Mustermann GmbH', type: 'document', link: '#', createdAt: '2026-02-20T09:00:00Z' },
      { id: 'o2', name: 'Landing Page — mustermann-recruiting.de', type: 'website', link: '#', createdAt: '2026-02-20T10:30:00Z' },
      { id: 'o3', name: 'Ad Copy Package — Mustermann', type: 'document', link: '#', createdAt: '2026-02-20T11:00:00Z' },
      { id: 'o4', name: 'Google Ads Kampagne — Mustermann', type: 'other', link: '#', createdAt: '2026-02-20T11:30:00Z' },
      { id: 'o5', name: 'Meta Ads Kampagne — Mustermann', type: 'other', link: '#', createdAt: '2026-02-20T11:45:00Z' },
      { id: 'o6', name: 'Content Package — 5 Blog-Artikel + Social Posts', type: 'document', link: '#', createdAt: '2026-02-20T12:00:00Z' },
      { id: 'o7', name: 'Performance Dashboard — Mustermann', type: 'spreadsheet', link: '#', createdAt: '2026-02-20T12:15:00Z' },
      { id: 'o8', name: 'Welcome Email — Mustermann GmbH', type: 'email', link: '#', createdAt: '2026-02-20T12:30:00Z' },
    ],
    lastExecuted: '2026-02-20T12:30:00Z',
    executionCount: 18,
  },

  // ── 2. Content Pipeline ──────────────────────────────────────────────────
  {
    id: 'demo-2',
    user_id: 'local-user',
    isDemo: true,
    name: 'Content Pipeline',
    description:
      'From content idea to finished blog post, social media post, and LinkedIn carousel.',
    category: 'Marketing',
    icon: 'type',
    status: 'active',
    webhookUrl: '',
    nodes: [
      {
        id: 'n1',
        label: 'Content Brief',
        description: 'Topic & audience defined',
        icon: 'clipboard',
        type: 'trigger',
        ...p(0, 0),
      },
      {
        id: 'n2',
        label: 'AI Research',
        description: 'Sources & data collected',
        icon: 'logo-openai',
        type: 'ai',
        ...p(1, 0),
      },
      {
        id: 'n3',
        label: 'Content Creation',
        description: 'Texts generated by AI',
        icon: 'logo-claude',
        type: 'ai',
        ...p(2, 0),
      },
      {
        id: 'n4',
        label: 'Blog Post',
        description: 'Article formatted & ready',
        icon: 'logo-notion',
        type: 'output',
        ...p(3, 0),
      },
      {
        id: 'n5',
        label: 'Social Media',
        description: 'Posts for all channels',
        icon: 'logo-meta',
        type: 'output',
        ...p(3, 1),
      },
      {
        id: 'n6',
        label: 'LinkedIn Carousel',
        description: 'Slides generated',
        icon: 'logo-linkedin',
        type: 'output',
        ...p(3, 2),
      },
    ],
    connections: [
      { from: 'n1', to: 'n2' },
      { from: 'n2', to: 'n3' },
      { from: 'n3', to: 'n4' },
      { from: 'n3', to: 'n5' },
      { from: 'n3', to: 'n6' },
    ],
    outputs: [
      {
        id: 'o1',
        name: 'Blog: AI in the Mid-Market',
        type: 'document',
        link: 'https://docs.google.com/document/d/blog1',
        createdAt: '2025-01-25T09:00:00Z',
      },
      {
        id: 'o2',
        name: 'Social Media Posts -- CW 04',
        type: 'document',
        link: 'https://docs.google.com/document/d/social1',
        createdAt: '2025-01-25T10:30:00Z',
      },
      {
        id: 'o3',
        name: 'LinkedIn Carousel -- AI Guide',
        type: 'image',
        link: 'https://drive.google.com/file/d/carousel1',
        createdAt: '2025-01-25T11:00:00Z',
      },
    ],
    lastExecuted: '2025-01-25T11:00:00Z',
    executionCount: 23,
  },

  // ── 3. Lead Qualification ────────────────────────────────────────────────
  {
    id: 'demo-3',
    user_id: 'local-user',
    isDemo: true,
    name: 'Lead Qualification',
    description:
      'Automatically enrich, score, and route incoming leads to the CRM.',
    category: 'Sales',
    icon: 'target',
    status: 'active',
    webhookUrl: '',
    nodes: [
      {
        id: 'n1',
        label: 'Lead Intake',
        description: 'New contact received',
        icon: 'logo-gmail',
        type: 'trigger',
        ...p(0, 0),
      },
      {
        id: 'n2',
        label: 'Data Enrichment',
        description: 'Company data appended',
        icon: 'database',
        type: 'process',
        ...p(1, 0),
      },
      {
        id: 'n3',
        label: 'AI Scoring',
        description: 'Lead quality assessed',
        icon: 'logo-openai',
        type: 'ai',
        ...p(2, 0),
      },
      {
        id: 'n4',
        label: 'CRM Entry',
        description: 'Created in HubSpot',
        icon: 'logo-hubspot',
        type: 'output',
        ...p(3, 0),
      },
      {
        id: 'n5',
        label: 'Follow-up Email',
        description: 'Personalised email sent',
        icon: 'logo-gmail',
        type: 'output',
        ...p(3, 1),
      },
      {
        id: 'n6',
        label: 'Team Notification',
        description: 'Sales team informed',
        icon: 'logo-slack',
        type: 'output',
        ...p(2, 1),
      },
    ],
    connections: [
      { from: 'n1', to: 'n2' },
      { from: 'n2', to: 'n3' },
      { from: 'n3', to: 'n4' },
      { from: 'n3', to: 'n5' },
      { from: 'n2', to: 'n6' },
    ],
    outputs: [
      {
        id: 'o1',
        name: 'Lead Report January 2025',
        type: 'spreadsheet',
        link: 'https://docs.google.com/spreadsheets/d/report1',
        createdAt: '2025-01-27T16:00:00Z',
      },
      {
        id: 'o2',
        name: 'Follow-up Email -- Mueller AG',
        type: 'email',
        link: 'https://mail.google.com/mail/example',
        createdAt: '2025-01-28T09:00:00Z',
      },
      {
        id: 'o3',
        name: 'CRM Update -- 12 new contacts',
        type: 'other',
        link: 'https://app.hubspot.com/contacts/example',
        createdAt: '2025-01-29T14:00:00Z',
      },
    ],
    lastExecuted: '2025-01-29T14:00:00Z',
    executionCount: 47,
  },

  // ── 4. Report Generator ──────────────────────────────────────────────────
  {
    id: 'demo-4',
    user_id: 'local-user',
    isDemo: true,
    name: 'Report Generator',
    description:
      'Collect data from multiple sources, analyse it, and distribute finished reports.',
    category: 'Operations',
    icon: 'bar-chart',
    status: 'draft',
    webhookUrl: '',
    nodes: [
      {
        id: 'n1a',
        label: 'Google Sheets Import',
        description: 'Data from Sheets',
        icon: 'logo-google-sheets',
        type: 'trigger',
        x: 40,
        y: 58,
      },
      {
        id: 'n1b',
        label: 'HubSpot Export',
        description: 'CRM data exported',
        icon: 'logo-hubspot',
        type: 'trigger',
        x: 40,
        y: 166,
      },
      {
        id: 'n2',
        label: 'Merge Data',
        description: 'Sources combined',
        icon: 'database',
        type: 'process',
        ...p(1, 0),
      },
      {
        id: 'n3',
        label: 'AI Analysis',
        description: 'Patterns & trends identified',
        icon: 'logo-openai',
        type: 'ai',
        ...p(2, 0),
      },
      {
        id: 'n4',
        label: 'Build Report',
        description: 'Report formatted',
        icon: 'logo-google-docs',
        type: 'process',
        ...p(3, 0),
      },
      {
        id: 'n5',
        label: 'PDF to Drive',
        description: 'Saved as PDF',
        icon: 'logo-google-drive',
        type: 'output',
        ...p(4, 0),
      },
      {
        id: 'n6',
        label: 'Dashboard',
        description: 'Live view updated',
        icon: 'bar-chart',
        type: 'output',
        x: 40 + 4 * 340,
        y: 58 + 108,
      },
      {
        id: 'n7',
        label: 'Email Delivery',
        description: 'Sent to team',
        icon: 'logo-gmail',
        type: 'output',
        x: 40 + 4 * 340,
        y: 58 + 2 * 108,
      },
    ],
    connections: [
      { from: 'n1a', to: 'n2' },
      { from: 'n1b', to: 'n2' },
      { from: 'n2', to: 'n3' },
      { from: 'n3', to: 'n4' },
      { from: 'n4', to: 'n5' },
      { from: 'n4', to: 'n6' },
      { from: 'n4', to: 'n7' },
    ],
    groups: [
      {
        id: 'g1',
        label: 'Data Sources',
        x: 15,
        y: 8,
        width: 280,
        height: 256,
        color: 'blue',
      },
      {
        id: 'g2',
        label: 'Analysis & Processing',
        x: 355,
        y: 8,
        width: 960,
        height: 148,
        color: 'purple',
      },
      {
        id: 'g3',
        label: 'Distribution',
        x: 1375,
        y: 8,
        width: 280,
        height: 364,
        color: 'green',
      },
    ],
    outputs: [
      {
        id: 'o1',
        name: 'Monthly Report December',
        type: 'document',
        link: 'https://docs.google.com/document/d/report-dec',
        createdAt: '2025-01-20T08:00:00Z',
      },
      {
        id: 'o2',
        name: 'Performance Dashboard Q4',
        type: 'website',
        link: 'https://dashboard.example.com/q4',
        createdAt: '2025-01-20T09:00:00Z',
      },
      {
        id: 'o3',
        name: 'Executive Summary Q4',
        type: 'document',
        link: 'https://docs.google.com/document/d/exec-q4',
        createdAt: '2025-01-22T10:00:00Z',
      },
    ],
    lastExecuted: '2025-01-22T10:00:00Z',
    executionCount: 8,
  },

  // ── 5. Multi-Channel Support Workflow (showcases new node types) ────────
  {
    id: 'demo-5',
    user_id: 'local-user',
    isDemo: true,
    name: 'Support Workflow',
    description:
      'Eingehende Support-Anfragen werden automatisch klassifiziert, geroutet und bearbeitet.',
    category: 'Support',
    icon: 'headphones',
    status: 'active',
    webhookUrl: '',
    nodes: [
      {
        id: 's1',
        label: 'Support-Eingang',
        description: 'Ticket empfangen',
        icon: 'mail',
        type: 'trigger',
        ...p(0, 1),
      },
      {
        id: 's2',
        label: 'KI-Klassifizierung',
        description: 'Ticket-Typ und Priorität erkennen',
        icon: 'brain-circuit',
        type: 'agent',
        ...p(1, 1),
      },
      {
        id: 's3',
        label: 'Priorität prüfen',
        description: 'Hoch oder Normal?',
        icon: 'git-branch',
        type: 'ifelse',
        ...p(2, 1),
      },
      {
        id: 's4',
        label: 'Manager-Freigabe',
        description: 'Genehmigung für Eskalation',
        icon: 'shield-check',
        type: 'approval',
        ...p(3, 0),
      },
      {
        id: 's5',
        label: 'Auto-Antwort',
        description: 'Standard-Antwort generieren',
        icon: 'logo-openai',
        type: 'ai',
        ...p(3, 2),
      },
      {
        id: 's6',
        label: 'Zusammenführen',
        description: 'Beide Pfade vereinen',
        icon: 'git-merge',
        type: 'merge',
        ...p(4, 1),
      },
      {
        id: 's7',
        label: 'Fehlerbehandlung',
        description: 'Bei Fehler: Team benachrichtigen',
        icon: 'alert-triangle',
        type: 'error-handler',
        ...p(3, 3),
      },
      {
        id: 's8',
        label: 'Warten auf Feedback',
        description: '24h auf Kunden-Antwort warten',
        icon: 'clock',
        type: 'wait',
        ...p(5, 1),
      },
      {
        id: 's9',
        label: 'Ticket-Routing',
        description: 'An richtiges Team weiterleiten',
        icon: 'shuffle',
        type: 'router',
        ...p(6, 1),
      },
      {
        id: 's10',
        label: 'Ticket geschlossen',
        description: 'Zusammenfassung an CRM',
        icon: 'check-circle',
        type: 'output',
        ...p(7, 1),
      },
    ],
    connections: [
      { from: 's1', to: 's2' },
      { from: 's2', to: 's3' },
      { from: 's3', to: 's4', label: 'Hoch' },
      { from: 's3', to: 's5', label: 'Normal' },
      { from: 's4', to: 's6' },
      { from: 's5', to: 's6' },
      { from: 's5', to: 's7' },
      { from: 's6', to: 's8' },
      { from: 's8', to: 's9' },
      { from: 's9', to: 's10' },
    ],
    groups: [
      {
        id: 'sg1',
        label: 'Klassifizierung',
        x: 15, y: 80,
        width: 620, height: 200,
        color: 'purple',
      },
      {
        id: 'sg2',
        label: 'Bearbeitung',
        x: 695, y: 8,
        width: 960, height: 400,
        color: 'blue',
      },
    ],
    outputs: [],
    lastExecuted: '2025-02-15T09:00:00Z',
    executionCount: 34,
  },
]

// ── Workflow Templates ─────────────────────────────────────────────────────

export const DEMO_TEMPLATES: WorkflowTemplate[] = [
  // ── 1. Lead Generation & Nurturing ───────────────────────────────────────
  {
    id: 'tpl-lead-gen',
    user_id: 'local-user',
    name: 'Lead Generation & Nurturing',
    description:
      'Capture leads from multiple channels, score them with AI, and nurture with automated email sequences.',
    category: 'Marketing',
    icon: 'target',
    nodeCount: 8,
    tags: ['leads', 'email', 'AI scoring', 'CRM'],
    nodes: [
      { id: 't1', label: 'Form Submission', description: 'Website form captured', icon: 'logo-zapier', type: 'trigger', ...p(0, 0) },
      { id: 't2', label: 'LinkedIn Ad', description: 'Lead ad conversion', icon: 'logo-linkedin', type: 'trigger', ...p(0, 1) },
      { id: 't3', label: 'Merge & Dedupe', description: 'Combine and clean leads', icon: 'database', type: 'process', ...p(1, 0) },
      { id: 't4', label: 'AI Lead Scoring', description: 'Score based on ICP fit', icon: 'logo-openai', type: 'ai', ...p(2, 0) },
      { id: 't5', label: 'Segment & Route', description: 'High/medium/low buckets', icon: 'split', type: 'process', ...p(3, 0) },
      { id: 't6', label: 'CRM Update', description: 'Create or update in CRM', icon: 'logo-hubspot', type: 'output', ...p(4, 0) },
      { id: 't7', label: 'Email Sequence', description: 'Nurture email drip', icon: 'logo-gmail', type: 'output', ...p(4, 1) },
      { id: 't8', label: 'Slack Alert', description: 'Notify sales team', icon: 'logo-slack', type: 'output', ...p(4, 2) },
    ],
    connections: [
      { from: 't1', to: 't3' },
      { from: 't2', to: 't3' },
      { from: 't3', to: 't4' },
      { from: 't4', to: 't5' },
      { from: 't5', to: 't6' },
      { from: 't5', to: 't7' },
      { from: 't5', to: 't8' },
    ],
    groups: [
      { id: 'tg1', label: 'Capture', x: 15, y: 8, width: 280, height: 256, color: 'blue' },
      { id: 'tg2', label: 'Scoring', x: 355, y: 8, width: 620, height: 148, color: 'purple' },
      { id: 'tg3', label: 'Activation', x: 1035, y: 8, width: 280, height: 364, color: 'green' },
    ],
  },

  // ── 2. Content Production Pipeline ───────────────────────────────────────
  {
    id: 'tpl-content-prod',
    user_id: 'local-user',
    name: 'Content Production Pipeline',
    description:
      'Research, draft, and distribute content across blog, social, and email from a single brief.',
    category: 'Marketing',
    icon: 'type',
    nodeCount: 7,
    tags: ['content', 'blog', 'social media', 'AI writing'],
    nodes: [
      { id: 't1', label: 'Content Brief', description: 'Topic and keywords', icon: 'clipboard', type: 'trigger', ...p(0, 0) },
      { id: 't2', label: 'Research Agent', description: 'Gather sources and data', icon: 'logo-openai', type: 'ai', ...p(1, 0) },
      { id: 't3', label: 'Draft Generator', description: 'Create long-form draft', icon: 'logo-claude', type: 'ai', ...p(2, 0) },
      { id: 't4', label: 'Blog Post', description: 'Publish to CMS', icon: 'logo-wordpress', type: 'output', ...p(3, 0) },
      { id: 't5', label: 'Social Posts', description: 'Adapt for channels', icon: 'logo-meta', type: 'output', ...p(3, 1) },
      { id: 't6', label: 'Newsletter', description: 'Add to email blast', icon: 'logo-gmail', type: 'output', ...p(3, 2) },
      { id: 't7', label: 'Analytics Tag', description: 'Track performance', icon: 'logo-google-analytics', type: 'output', ...p(4, 0) },
    ],
    connections: [
      { from: 't1', to: 't2' },
      { from: 't2', to: 't3' },
      { from: 't3', to: 't4' },
      { from: 't3', to: 't5' },
      { from: 't3', to: 't6' },
      { from: 't4', to: 't7' },
    ],
  },

  // ── 3. Client Reporting Automation ───────────────────────────────────────
  {
    id: 'tpl-client-report',
    user_id: 'local-user',
    name: 'Client Reporting Automation',
    description:
      'Pull metrics from ad platforms and analytics, generate AI summaries, and deliver polished client reports.',
    category: 'Operations',
    icon: 'bar-chart',
    nodeCount: 6,
    tags: ['reporting', 'analytics', 'PDF', 'clients'],
    nodes: [
      { id: 't1', label: 'Scheduled Trigger', description: 'Monthly cadence', icon: 'timer', type: 'trigger', ...p(0, 0) },
      { id: 't2', label: 'Pull Metrics', description: 'Ads + Analytics data', icon: 'logo-google-analytics', type: 'process', ...p(1, 0) },
      { id: 't3', label: 'AI Summary', description: 'Generate insights', icon: 'logo-openai', type: 'ai', ...p(2, 0) },
      { id: 't4', label: 'Build Report', description: 'Format in template', icon: 'logo-google-docs', type: 'process', ...p(3, 0) },
      { id: 't5', label: 'Save to Drive', description: 'Archive as PDF', icon: 'logo-google-drive', type: 'output', ...p(4, 0) },
      { id: 't6', label: 'Send to Client', description: 'Email with attachment', icon: 'logo-gmail', type: 'output', ...p(4, 1) },
    ],
    connections: [
      { from: 't1', to: 't2' },
      { from: 't2', to: 't3' },
      { from: 't3', to: 't4' },
      { from: 't4', to: 't5' },
      { from: 't4', to: 't6' },
    ],
  },

  // ── 4. Marketing Agency Fulfillment ──────────────────────────────────────
  {
    id: 'tpl-agency',
    user_id: 'local-user',
    name: 'Marketing Agency Fulfillment',
    description:
      'End-to-end client fulfillment: onboarding, content, ads, and reporting in a single workflow.',
    category: 'Operations',
    icon: 'workflow',
    nodeCount: 9,
    tags: ['agency', 'onboarding', 'ads', 'reporting', 'full-service'],
    nodes: [
      { id: 't1', label: 'New Client', description: 'Onboarding form submitted', icon: 'users', type: 'trigger', ...p(0, 0) },
      { id: 't2', label: 'AI Briefing', description: 'Extract strategy from call', icon: 'logo-openai', type: 'ai', ...p(1, 0) },
      { id: 't3', label: 'Generate Website', description: 'Build landing page', icon: 'globe', type: 'process', ...p(2, 0) },
      { id: 't4', label: 'Write Ad Copy', description: 'Create campaign text', icon: 'logo-claude', type: 'ai', ...p(2, 1) },
      { id: 't5', label: 'Setup Google Ads', description: 'Configure campaigns', icon: 'logo-google-ads', type: 'output', ...p(3, 0) },
      { id: 't6', label: 'Setup Meta Ads', description: 'Facebook & Instagram', icon: 'logo-meta', type: 'output', ...p(3, 1) },
      { id: 't7', label: 'Tracking Setup', description: 'Analytics & pixels', icon: 'logo-google-analytics', type: 'process', ...p(3, 2) },
      { id: 't8', label: 'Client Dashboard', description: 'Real-time metrics', icon: 'bar-chart', type: 'output', ...p(4, 1) },
      { id: 't9', label: 'Welcome Email', description: 'Credentials & timeline', icon: 'logo-gmail', type: 'output', ...p(4, 0) },
    ],
    connections: [
      { from: 't1', to: 't2' },
      { from: 't2', to: 't3' },
      { from: 't2', to: 't4' },
      { from: 't3', to: 't5' },
      { from: 't4', to: 't5' },
      { from: 't4', to: 't6' },
      { from: 't5', to: 't7' },
      { from: 't6', to: 't7' },
      { from: 't7', to: 't8' },
      { from: 't3', to: 't9' },
    ],
    groups: [
      { id: 'tg1', label: 'Onboarding', x: 15, y: 8, width: 280, height: 148, color: 'blue' },
      { id: 'tg2', label: 'Production', x: 355, y: 8, width: 620, height: 256, color: 'purple' },
      { id: 'tg3', label: 'Launch & Monitor', x: 1035, y: 8, width: 280, height: 256, color: 'green' },
    ],
  },

  // ── 5. Recruiting Fulfillment ──────────────────────────────────────────────
  {
    id: 'tpl-recruiting',
    user_id: 'local-user',
    name: 'Recruiting Fulfillment',
    description: 'Vom Kickoff-Call über Knowledge Processing und Content-Produktion bis zum Launch mit Performance-Tracking.',
    category: 'Recruiting',
    icon: 'building-2',
    nodeCount: 12,
    tags: ['recruiting', 'agentur', 'fulfillment', 'KI'],
    nodes: [
      { id: 'rc1', label: 'Client Handover', description: 'Formular von Sales', icon: 'clipboard-check', type: 'trigger', ...p(0, 0) },
      { id: 'rc2', label: 'CRM Setup', description: 'Pipeline & Tags anlegen', icon: 'logo-hubspot', type: 'process', ...p(1, 0) },
      { id: 'rc3', label: 'Onboarding Call', description: 'Standardisiertes Gespräch', icon: 'video', type: 'process', ...p(2, 0) },
      { id: 'rc4', label: 'KI-Transkription', description: 'Call transkribieren & analysieren', icon: 'logo-openai', type: 'ai', ...p(3, 0) },
      { id: 'rc5', label: 'Daten extrahieren', description: 'Pain Points, Benefits, Messaging', icon: 'logo-claude', type: 'ai', ...p(4, 0) },
      { id: 'rc6', label: 'Website Copy', description: 'Landing Page Texte generieren', icon: 'logo-claude', type: 'ai', ...p(5, 0) },
      { id: 'rc7', label: 'Ad Copy', description: 'Meta & Google Anzeigentexte', icon: 'logo-claude', type: 'ai', ...p(5, 1) },
      { id: 'rc8', label: 'Website bauen', description: 'Template + Copy → Live', icon: 'globe', type: 'process', ...p(6, 0) },
      { id: 'rc9', label: 'Kampagnen Setup', description: 'Ads vorbereiten & starten', icon: 'logo-meta', type: 'output', ...p(6, 1) },
      { id: 'rc10', label: 'Review & Freigabe', description: 'Qualitätsprüfung', icon: 'shield-check', type: 'process', ...p(7, 0) },
      { id: 'rc11', label: 'Go Live', description: 'Alles live schalten', icon: 'rocket', type: 'output', ...p(8, 0) },
      { id: 'rc12', label: 'Performance Tracking', description: 'KPIs überwachen', icon: 'bar-chart', type: 'output', ...p(8, 1) },
    ],
    connections: [
      { from: 'rc1', to: 'rc2' },
      { from: 'rc2', to: 'rc3' },
      { from: 'rc3', to: 'rc4' },
      { from: 'rc4', to: 'rc5' },
      { from: 'rc5', to: 'rc6' }, { from: 'rc5', to: 'rc7' },
      { from: 'rc6', to: 'rc8' }, { from: 'rc7', to: 'rc9' },
      { from: 'rc8', to: 'rc10' }, { from: 'rc9', to: 'rc10' },
      { from: 'rc10', to: 'rc11' }, { from: 'rc10', to: 'rc12' },
    ],
    groups: [
      { id: 'trg1', label: 'Onboarding', x: 15, y: 8, width: 620, height: 148, color: 'blue' },
      { id: 'trg2', label: 'Knowledge Processing', x: 695, y: 8, width: 620, height: 148, color: 'purple' },
      { id: 'trg3', label: 'Produktion', x: 1375, y: 8, width: 620, height: 256, color: 'green' },
      { id: 'trg4', label: 'Launch & Tracking', x: 2055, y: 8, width: 620, height: 256, color: 'orange' },
    ],
  },

  // ── 6. Buchhaltung & Rechnungen ────────────────────────────────────────────
  {
    id: 'tpl-buchhaltung',
    user_id: 'local-user',
    name: 'Buchhaltung & Rechnungen',
    description: 'Eingangsrechnungen erfassen, Ausgangsrechnungen erstellen, Mahnwesen und Monatsabschluss automatisieren.',
    category: 'Operations',
    icon: 'receipt',
    nodeCount: 10,
    tags: ['buchhaltung', 'rechnungen', 'mahnwesen', 'finanzen'],
    nodes: [
      { id: 'bk1', label: 'Rechnung eingehend', description: 'PDF per Mail oder Upload', icon: 'logo-gmail', type: 'trigger', ...p(0, 0) },
      { id: 'bk2', label: 'KI-Extraktion', description: 'Betrag, Datum, Lieferant extrahieren', icon: 'logo-openai', type: 'ai', ...p(1, 0) },
      { id: 'bk3', label: 'Buchhaltung buchen', description: 'Automatisch kontieren', icon: 'database', type: 'process', ...p(2, 0) },
      { id: 'bk4', label: 'Freigabe anfordern', description: 'Manager muss bestätigen', icon: 'shield-check', type: 'process', ...p(3, 0) },
      { id: 'bk5', label: 'Zahlung auslösen', description: 'Überweisung vorbereiten', icon: 'logo-stripe', type: 'output', ...p(4, 0) },
      { id: 'bk6', label: 'Ausgangsrechnung', description: 'Rechnung aus Vorlage erstellen', icon: 'logo-google-docs', type: 'process', ...p(0, 2) },
      { id: 'bk7', label: 'Versand an Client', description: 'Per Mail mit PDF-Anhang', icon: 'logo-gmail', type: 'output', ...p(1, 2) },
      { id: 'bk8', label: 'Zahlungseingang prüfen', description: 'Bankabgleich', icon: 'database', type: 'process', ...p(2, 2) },
      { id: 'bk9', label: 'Mahnung versenden', description: 'Bei Zahlungsverzug', icon: 'logo-gmail', type: 'output', ...p(3, 2) },
      { id: 'bk10', label: 'Monatsabschluss', description: 'BWA & Summary generieren', icon: 'logo-google-sheets', type: 'output', ...p(4, 2) },
    ],
    connections: [
      { from: 'bk1', to: 'bk2' },
      { from: 'bk2', to: 'bk3' },
      { from: 'bk3', to: 'bk4' },
      { from: 'bk4', to: 'bk5' },
      { from: 'bk6', to: 'bk7' },
      { from: 'bk7', to: 'bk8' },
      { from: 'bk8', to: 'bk9' },
      { from: 'bk8', to: 'bk10' },
    ],
    groups: [
      { id: 'tbg1', label: 'Eingangsrechnungen', x: 15, y: 8, width: 1380, height: 148, color: 'blue' },
      { id: 'tbg2', label: 'Ausgangsrechnungen & Mahnwesen', x: 15, y: 196, width: 1380, height: 148, color: 'green' },
    ],
  },

  // ── 7. Coach Inbox Copilot ─────────────────────────────────────────────────
  {
    id: 'tpl-coach-inbox',
    user_id: 'local-user',
    name: 'Coach Inbox Copilot',
    description: 'Eingehende E-Mails klassifizieren, FAQ automatisch beantworten, individuelle Antworten vorbereiten und Reminder setzen.',
    category: 'Support',
    icon: 'headphones',
    nodeCount: 9,
    tags: ['coaching', 'inbox', 'email', 'KI-Assistent'],
    nodes: [
      { id: 'ci1', label: 'E-Mail Eingang', description: 'Neue Nachricht empfangen', icon: 'logo-gmail', type: 'trigger', ...p(0, 0) },
      { id: 'ci2', label: 'KI-Klassifizierung', description: 'Kategorie & Dringlichkeit erkennen', icon: 'logo-openai', type: 'ai', ...p(1, 0) },
      { id: 'ci3', label: 'FAQ oder Individuell?', description: 'Routing-Entscheidung', icon: 'git-branch', type: 'process', ...p(2, 0) },
      { id: 'ci4', label: 'FAQ-Antwort', description: 'Standard-Antwort aus Wissensbasis', icon: 'logo-openai', type: 'ai', ...p(3, 0) },
      { id: 'ci5', label: 'Individuelle Antwort', description: 'KI-Draft mit Coach-Review', icon: 'logo-claude', type: 'ai', ...p(3, 1) },
      { id: 'ci6', label: 'Freigabe', description: 'Coach prüft und bestätigt', icon: 'shield-check', type: 'process', ...p(4, 0) },
      { id: 'ci7', label: 'Antwort senden', description: 'E-Mail versenden', icon: 'logo-gmail', type: 'output', ...p(5, 0) },
      { id: 'ci8', label: 'CRM Update', description: 'Interaktion dokumentieren', icon: 'logo-hubspot', type: 'output', ...p(5, 1) },
      { id: 'ci9', label: 'Reminder setzen', description: 'Follow-up in X Tagen', icon: 'clock', type: 'output', ...p(6, 0) },
    ],
    connections: [
      { from: 'ci1', to: 'ci2' },
      { from: 'ci2', to: 'ci3' },
      { from: 'ci3', to: 'ci4' }, { from: 'ci3', to: 'ci5' },
      { from: 'ci4', to: 'ci6' }, { from: 'ci5', to: 'ci6' },
      { from: 'ci6', to: 'ci7' }, { from: 'ci6', to: 'ci8' },
      { from: 'ci7', to: 'ci9' },
    ],
    groups: [
      { id: 'tcg1', label: 'Erfassung & Klassifizierung', x: 15, y: 8, width: 620, height: 148, color: 'purple' },
      { id: 'tcg2', label: 'Antwort-Generierung', x: 695, y: 8, width: 620, height: 256, color: 'blue' },
      { id: 'tcg3', label: 'Versand & Follow-up', x: 1375, y: 8, width: 620, height: 256, color: 'green' },
    ],
  },
]
