import type { FunnelBoard } from './types'

/**
 * Demo Funnel Boards – werden beim ersten Laden in den Store geladen.
 * Basiert auf dem Legacy "Lead-Generierung Funnel" aus der Ai Automation V1.
 */
export const DEMO_FUNNEL_BOARDS: FunnelBoard[] = [
  {
    id: 'demo-funnel-1',
    name: 'Lead-Generierung Funnel',
    description: 'Facebook Ads → Landing Page → Formular → E-Mail Sequenz',
    elements: [
      {
        id: 'df-el-1',
        type: 'platform',
        x: 80,
        y: 140,
        width: 200,
        height: 80,
        platformKind: 'facebook-ads',
        label: 'Facebook Ads',
        icon: 'logo-meta',
        description: 'Lookalike Audience',
        metricLabel: 'Budget',
        metricValue: '€2.500/Mo',
      },
      {
        id: 'df-el-2',
        type: 'platform',
        x: 380,
        y: 140,
        width: 200,
        height: 80,
        platformKind: 'landingpage',
        label: 'Landing Page',
        icon: 'globe',
        description: 'Opt-in mit Lead Magnet',
        metricLabel: 'CTR',
        metricValue: '3.2%',
      },
      {
        id: 'df-el-3',
        type: 'platform',
        x: 680,
        y: 140,
        width: 200,
        height: 80,
        platformKind: 'formular',
        label: 'Kontaktformular',
        icon: 'file-text',
        description: 'Name, E-Mail, Telefon',
        metricLabel: 'Conv.',
        metricValue: '12%',
      },
      {
        id: 'df-el-4',
        type: 'platform',
        x: 980,
        y: 140,
        width: 200,
        height: 80,
        platformKind: 'email',
        label: 'E-Mail Sequenz',
        icon: 'mail',
        description: '5-teilige Nurture-Sequenz',
        metricLabel: 'Open',
        metricValue: '45%',
      },
      {
        id: 'df-el-5',
        type: 'platform',
        x: 1280,
        y: 140,
        width: 200,
        height: 80,
        platformKind: 'kalender',
        label: 'Kalender-Buchung',
        icon: 'logo-calendly',
        description: 'Erstgespräch buchen',
        metricLabel: 'Buchungen',
        metricValue: '8/Wo',
      },
      {
        id: 'df-el-6',
        type: 'text',
        x: 80,
        y: 50,
        width: 400,
        height: 48,
        textKind: 'headline',
        textContent: 'Lead-Generierung Funnel',
        fontSize: 24,
        fontWeight: 'bold',
      },
      {
        id: 'df-el-7',
        type: 'text',
        x: 80,
        y: 260,
        width: 300,
        height: 36,
        textKind: 'note',
        textContent: 'Ziel: 40 qualifizierte Leads/Monat',
        fontSize: 12,
        fontWeight: 'normal',
        textColor: '#6b7280',
      },
    ],
    connections: [
      { id: 'df-cn-1', from: 'df-el-1', to: 'df-el-2', fromPort: 'right', toPort: 'left', label: 'Klick' },
      { id: 'df-cn-2', from: 'df-el-2', to: 'df-el-3', fromPort: 'right', toPort: 'left', label: 'Absenden' },
      { id: 'df-cn-3', from: 'df-el-3', to: 'df-el-4', fromPort: 'right', toPort: 'left', label: 'Trigger' },
      { id: 'df-cn-4', from: 'df-el-4', to: 'df-el-5', fromPort: 'right', toPort: 'left', label: 'CTA' },
    ],
    phases: [
      { id: 'df-ph-1', label: 'Awareness', x: 50, y: 100, width: 270, height: 180, color: '#3b82f6' },
      { id: 'df-ph-2', label: 'Interest', x: 350, y: 100, width: 270, height: 180, color: '#8b5cf6' },
      { id: 'df-ph-3', label: 'Conversion', x: 650, y: 100, width: 270, height: 180, color: '#10b981' },
      { id: 'df-ph-4', label: 'Nurture', x: 950, y: 100, width: 570, height: 180, color: '#f97316' },
    ],
    createdAt: '2026-01-15T10:00:00.000Z',
    updatedAt: '2026-02-20T14:30:00.000Z',
  },
  {
    id: 'demo-funnel-2',
    name: 'E-Commerce Checkout',
    description: 'Google Ads → Website → Checkout → Follow-Up',
    elements: [
      {
        id: 'df2-el-1',
        type: 'platform',
        x: 80,
        y: 140,
        width: 200,
        height: 80,
        platformKind: 'google-ads',
        label: 'Google Ads',
        icon: 'logo-google-ads',
        description: 'Search + Shopping',
        metricLabel: 'CPC',
        metricValue: '€1.20',
      },
      {
        id: 'df2-el-2',
        type: 'platform',
        x: 380,
        y: 140,
        width: 200,
        height: 80,
        platformKind: 'website',
        label: 'Shop-Website',
        icon: 'globe',
        description: 'Produktseiten',
      },
      {
        id: 'df2-el-3',
        type: 'platform',
        x: 680,
        y: 140,
        width: 200,
        height: 80,
        platformKind: 'checkout',
        label: 'Checkout',
        icon: 'logo-stripe',
        description: 'Stripe Payment',
        metricLabel: 'AOV',
        metricValue: '€89',
      },
      {
        id: 'df2-el-4',
        type: 'platform',
        x: 980,
        y: 140,
        width: 200,
        height: 80,
        platformKind: 'email',
        label: 'Follow-Up E-Mail',
        icon: 'mail',
        description: 'Bestellbestätigung + Upsell',
      },
    ],
    connections: [
      { id: 'df2-cn-1', from: 'df2-el-1', to: 'df2-el-2', fromPort: 'right', toPort: 'left', label: 'Klick' },
      { id: 'df2-cn-2', from: 'df2-el-2', to: 'df2-el-3', fromPort: 'right', toPort: 'left', label: 'Kauf' },
      { id: 'df2-cn-3', from: 'df2-el-3', to: 'df2-el-4', fromPort: 'right', toPort: 'left', label: 'Bestätigung' },
    ],
    phases: [
      { id: 'df2-ph-1', label: 'Awareness', x: 50, y: 100, width: 270, height: 180, color: '#3b82f6' },
      { id: 'df2-ph-2', label: 'Interest', x: 350, y: 100, width: 270, height: 180, color: '#8b5cf6' },
      { id: 'df2-ph-3', label: 'Conversion', x: 650, y: 100, width: 570, height: 180, color: '#10b981' },
    ],
    createdAt: '2026-01-20T10:00:00.000Z',
    updatedAt: '2026-02-18T09:00:00.000Z',
  },
]
