import type { AutomationSystem, WorkflowTemplate } from './types'

/**
 * Grid position helper — accounts for largest node sizes (subsystem: 320×130).
 *
 * x = 40 + column * 380  (320px max width + 60px gap)
 * y: 40 + row    * 160  (130px max height + 30px gap)
 */
const p = (col: number, row: number) => ({
  x: 40 + col * 380,
  y: 40 + row * 160,
})

// ── Demo Automation Systems ────────────────────────────────────────────────

export const DEMO_SYSTEMS: AutomationSystem[] = [
  // ── 0. Novacode Recruiting Automation (Master with Sub-Systems) ─────────────
  {
    id: 'demo-novacode',
    user_id: 'local-user',
    isDemo: true,
    name: 'Novacode Recruiting Automation',
    description: 'Agentur-Fulfillment-Automation: Vom Onboarding-Formular über Infrastruktur-Setup, Kickoff, Strategie, Text-Erstellung, Funnel, Kampagnen bis zum Go-Live — mit echten API-Integrationen (Close CRM, Google Workspace, Slack, Meta Ads).',
    category: 'Recruiting',
    icon: 'building-2',
    status: 'active',
    webhookUrl: '',
    nodes: [
      { id: 'nc-t1', label: 'Onboarding-Formular', description: 'Offizieller Trigger: Alle Client-Daten erfasst', icon: 'clipboard-check', type: 'trigger', x: 60, y: 200, demoConfig: { delay: 3000, artifacts: [{ type: 'text', label: 'Onboarding-Formular eingegangen', url: '#', contentPreview: 'Onboarding-Formular eingegangen — Novacode GmbH' }] } },
      { id: 'nc-t2', label: 'Daten validieren', description: 'Formulardaten prüfen und bereinigen', icon: 'git-merge', type: 'process', x: 340, y: 200, demoConfig: { delay: 4000, artifacts: [{ type: 'text', label: 'Daten validiert', url: '#', contentPreview: 'Daten validiert: Firma, Ansprechpartner, Servicetyp, Termin' }] } },
    ],
    connections: [
      { from: 'nc-t1', to: 'nc-t2' },
      { from: 'nc-t2', to: 'sub-demo-novacode-infra' },
      { from: 'sub-demo-novacode-infra', to: 'sub-demo-novacode-kickoff' },
      { from: 'sub-demo-novacode-kickoff', to: 'sub-demo-novacode-strategy' },
      { from: 'sub-demo-novacode-strategy', to: 'sub-demo-novacode-copy' },
      { from: 'sub-demo-novacode-copy', to: 'sub-demo-novacode-funnel' },
      { from: 'sub-demo-novacode-funnel', to: 'sub-demo-novacode-campaigns' },
      { from: 'sub-demo-novacode-campaigns', to: 'sub-demo-novacode-launch' },
    ],
    groups: [],
    outputs: [],
    lastExecuted: '2026-02-25T14:00:00Z',
    executionCount: 3,
  },

  // ── 0a. Infrastruktur-Setup (Sub-System) ──────────────────────────────────
  {
    id: 'demo-novacode-infra',
    user_id: 'local-user',
    isDemo: true,
    parentId: 'demo-novacode',
    subSystemOrder: 0,
    name: 'Infrastruktur-Setup',
    description: 'Close CRM Pipeline, Google Drive Ordner, Calendar Event, Willkommens-E-Mail, Slack & ClickUp — komplettes Client-Setup.',
    category: 'Recruiting',
    icon: 'folder-open',
    status: 'active',
    webhookUrl: '',
    nodes: [
      { id: 'is01', label: 'Handover-Daten', description: 'Formular-Daten übernommen', icon: 'clipboard-check', type: 'trigger', x: 40, y: 198, demoConfig: { delay: 3000, artifacts: [{ type: 'text', label: 'Handover-Daten empfangen', url: '#', contentPreview: 'Handover-Formulardaten für Novacode GmbH empfangen und bereit zur Verarbeitung' }] } },
      { id: 'is02', label: 'Close: Lead erstellen', description: 'Lead + Fulfillment Pipeline + Stage \'Onboarding gestartet\'', icon: 'logo-close', type: 'process', x: 380, y: 198, demoConfig: { delay: 8000, artifacts: [{ type: 'url', label: 'Close CRM: Lead erstellt', url: 'https://app.close.com/pipeline/pipe_2Zs3qMCbUuykBfzFT8qDdh/', contentPreview: 'Close CRM: Lead \'Novacode GmbH\' erstellt, Pipeline Fulfillment, Phase Onboarding gestartet' }] } },
      { id: 'is03', label: 'Slack: Neuer Client', description: 'Ops-Channel: Client-Info, Links, Team', icon: 'logo-slack', type: 'output', x: 720, y: 18, demoConfig: { delay: 5000, artifacts: [{ type: 'url', label: 'Slack: Neuer Client', url: 'https://app.slack.com/', contentPreview: 'Slack: Neuer Client Novacode GmbH — Channel erstellt + Ops benachrichtigt' }] } },
      { id: 'is04', label: 'Willkommens-E-Mail', description: 'Kickoff-Info, Vorbereitung, Upload-Link', icon: 'logo-gmail', type: 'output', x: 720, y: 198, demoConfig: { delay: 6000, artifacts: [{ type: 'url', label: 'Willkommens-E-Mail gesendet', url: 'https://mail.google.com/', contentPreview: 'Willkommens-E-Mail an clazahlungskonto@gmail.com gesendet' }] } },
      { id: 'is05', label: 'Kickoff-Termin', description: 'Google Calendar + Meet Link', icon: 'logo-google-calendar', type: 'output', x: 720, y: 378, demoConfig: { delay: 7000, artifacts: [{ type: 'url', label: 'Kickoff-Termin erstellt', url: 'https://calendar.google.com/calendar/u/0/r', contentPreview: 'Kickoff-Termin: Google Calendar Event mit Google Meet erstellt' }] } },
      { id: 'is06', label: 'Drive: Ordnerstruktur', description: '8 Hauptordner + Unterordner laut Spec', icon: 'logo-google-drive', type: 'output', x: 1060, y: 18, demoConfig: { delay: 15000, artifacts: [{ type: 'url', label: 'Google Drive: Ordnerstruktur', url: 'https://drive.google.com/drive/folders/146HuSG1oBlTmrGlYsbhqkIIkp1OgrbNR?dmr=1&ec=wgc-drive-globalnav-goto', contentPreview: '8 Ordner erstellt: 01_Administration bis 08_Transcripts' }] } },
      { id: 'is07', label: 'Drive: Templates', description: 'Tracking Dashboard + Onboarding Brief dupliziert', icon: 'logo-google-docs', type: 'output', x: 1400, y: 18, demoConfig: { delay: 8000, artifacts: [{ type: 'url', label: 'Drive: Templates dupliziert', url: 'https://drive.google.com/drive/folders/146HuSG1oBlTmrGlYsbhqkIIkp1OgrbNR?dmr=1&ec=wgc-drive-globalnav-goto', contentPreview: 'Templates dupliziert: Tracking Dashboard + Onboarding Brief' }] } },
      { id: 'is08', label: 'ClickUp: Projekt', description: 'Novacode – Recruiting Projekt anlegen', icon: 'logo-clickup', type: 'process', x: 1060, y: 378, demoConfig: { delay: 10000, artifacts: [{ type: 'url', label: 'ClickUp: Projekt erstellt', url: 'https://app.clickup.com/90189542355', contentPreview: 'ClickUp: Projekt \'Novacode – Recruiting\' in Client Projects erstellt' }] } },
      { id: 'is09', label: 'ClickUp: Tasks', description: 'Zugang prüfen + Kickoff vorbereiten + Checklisten', icon: 'logo-clickup', type: 'process', x: 1400, y: 378, demoConfig: { delay: 12000, artifacts: [{ type: 'url', label: 'ClickUp: Tasks erstellt', url: 'https://app.clickup.com/90189542355', contentPreview: 'ClickUp: Tasks mit Checklisten erstellt (Zugänge + Kickoff)' }] } },
      { id: 'is10', label: 'Close: Kickoff geplant', description: 'Phase → Kickoff geplant, Status → Warte auf Kickoff', icon: 'logo-close', type: 'process', x: 1740, y: 198, demoConfig: { delay: 5000, artifacts: [{ type: 'url', label: 'Close CRM: Status aktualisiert', url: 'https://app.close.com/pipeline/pipe_2Zs3qMCbUuykBfzFT8qDdh/', contentPreview: 'Close CRM: Phase → Kickoff geplant, Automations-Status → Warte auf Kickoff' }] } },
    ],
    connections: [
      { from: 'is01', to: 'is02' },
      { from: 'is02', to: 'is03' }, { from: 'is02', to: 'is04' }, { from: 'is02', to: 'is05' },
      { from: 'is02', to: 'is06' },
      { from: 'is02', to: 'is08' },
      { from: 'is06', to: 'is07' },
      { from: 'is08', to: 'is09' },
      { from: 'is07', to: 'is10' }, { from: 'is09', to: 'is10' },
    ],
    groups: [
      { id: 'gis1', label: 'Eingang', x: 15, y: 138, width: 620, height: 148, color: 'blue' },
      { id: 'gis2', label: 'Kommunikation', x: 695, y: 0, width: 280, height: 450, color: 'blue' },
      { id: 'gis3', label: 'Dateien & Projekt', x: 1035, y: 0, width: 620, height: 450, color: 'purple' },
      { id: 'gis4', label: 'Abschluss', x: 1715, y: 138, width: 280, height: 148, color: 'green' },
    ],
    outputs: [],
    executionCount: 0,
  },

  // ── 0b. Kickoff & Transkript (Sub-System) ─────────────────────────────────
  {
    id: 'demo-novacode-kickoff',
    user_id: 'local-user',
    isDemo: true,
    parentId: 'demo-novacode',
    subSystemOrder: 1,
    name: 'Kickoff & Transkript',
    description: 'Kickoff Call durchführen, aufzeichnen, KI-Transkription erstellen und als strategischen Input speichern.',
    category: 'Recruiting',
    icon: 'video',
    status: 'active',
    webhookUrl: '',
    nodes: [
      { id: 'kc01', label: 'Kickoff starten', description: 'Onboarding-Call mit Client starten', icon: 'video', type: 'trigger', x: 40, y: 198, demoConfig: { delay: 3000, artifacts: [{ type: 'text', label: 'Kickoff gestartet', url: '#', contentPreview: 'Kickoff-Call mit Novacode GmbH gestartet' }] } },
      { id: 'kc02', label: 'Call aufzeichnen', description: 'Aufzeichnung + Notizen erstellen', icon: 'video', type: 'process', x: 380, y: 198, demoConfig: { delay: 5000, artifacts: [{ type: 'text', label: 'Call-Aufzeichnung', url: '#', contentPreview: 'Call aufgezeichnet: 47 Min, Themen: Kandidatenprofil, Recruiting-Probleme, USPs, Brand & Design' }] } },
      { id: 'kc03', label: 'KI-Transkription', description: 'Transkribieren, strukturieren, Themen identifizieren', icon: 'logo-openai', type: 'ai', x: 720, y: 198, demoConfig: { delay: 10000, artifacts: [{ type: 'url', label: 'KI-Transkription', url: 'https://docs.google.com/document/d/1ZO6yLLW18GLjJd1xuCc8jytaGwPi0jedoSkUR8LO-eM/edit', contentPreview: 'KI-Transkription: 8.432 Wörter, 23 Schlüsselthemen' }] } },
      { id: 'kc04', label: 'Transkript speichern', description: 'In 08_Transcripts ablegen', icon: 'logo-google-docs', type: 'output', x: 1060, y: 118, demoConfig: { delay: 5000, artifacts: [{ type: 'url', label: 'Transkript gespeichert', url: 'https://docs.google.com/document/d/1ZO6yLLW18GLjJd1xuCc8jytaGwPi0jedoSkUR8LO-eM/edit', contentPreview: 'Transkript in 08_Transcripts gespeichert' }] } },
      { id: 'kc05', label: 'Close: Kickoff abgeschlossen', description: 'Phase → Kickoff abgeschlossen, Status → Strategie in Arbeit', icon: 'logo-close', type: 'process', x: 1060, y: 298, demoConfig: { delay: 5000, artifacts: [{ type: 'url', label: 'Close CRM: Status aktualisiert', url: 'https://app.close.com/pipeline/pipe_2Zs3qMCbUuykBfzFT8qDdh/', contentPreview: 'Close CRM: Phase → Kickoff abgeschlossen, Automations-Status → Strategie in Arbeit' }] } },
      { id: 'kc06', label: 'Slack: Call fertig', description: 'Team über erfolgreichen Call informieren', icon: 'logo-slack', type: 'output', x: 1400, y: 198, demoConfig: { delay: 4000, artifacts: [{ type: 'url', label: 'Slack: Kickoff abgeschlossen', url: 'https://app.slack.com/', contentPreview: 'Slack: Kickoff mit Novacode abgeschlossen, Transkript verfügbar' }] } },
    ],
    connections: [
      { from: 'kc01', to: 'kc02' },
      { from: 'kc02', to: 'kc03' },
      { from: 'kc03', to: 'kc04' },
      { from: 'kc03', to: 'kc05' },
      { from: 'kc04', to: 'kc06' },
      { from: 'kc05', to: 'kc06' },
    ],
    groups: [
      { id: 'gkc1', label: 'Kickoff Call', x: 15, y: 138, width: 960, height: 148, color: 'blue' },
      { id: 'gkc2', label: 'Ergebnis & Update', x: 1035, y: 58, width: 620, height: 308, color: 'green' },
    ],
    outputs: [],
    executionCount: 0,
  },

  // ── 0c. Strategie & Markenentwicklung (Sub-System) ────────────────────────
  {
    id: 'demo-novacode-strategy',
    user_id: 'local-user',
    isDemo: true,
    parentId: 'demo-novacode',
    subSystemOrder: 2,
    name: 'Strategie & Markenentwicklung',
    description: 'KI-Analyse des Transkripts, strategische Dokumente erstellen: Zielgruppe, Arbeitgeber-Avatar, Messaging, Creative Brief, Brand Guidelines.',
    category: 'Recruiting',
    icon: 'sparkles',
    status: 'active',
    webhookUrl: '',
    nodes: [
      { id: 'st01', label: 'Transkript-Analyse', description: 'Schlüsselthemen, Sentiment, Kernaussagen', icon: 'logo-openai', type: 'ai', x: 40, y: 238, demoConfig: { delay: 18000, artifacts: [{ type: 'text', label: 'Transkript-Analyse', url: '#', contentPreview: 'Transkript-Analyse: Schlüsselthemen, Sentiment, Kernaussagen identifiziert' }] } },
      { id: 'st02', label: 'Daten extrahieren', description: 'Pain Points, Benefits, Sprachmuster', icon: 'logo-claude', type: 'ai', x: 380, y: 238, demoConfig: { delay: 22000, artifacts: [{ type: 'url', label: 'Pain-Point-Matrix', url: 'https://docs.google.com/document/d/1RfNMSovKZx43uHrKDNa8G6iBCi_ouRTfShVuoLcuUac/edit', contentPreview: '8 Pain Points, 12 Benefits, 5 Sprachmuster extrahiert' }] } },
      { id: 'st03', label: 'Zielgruppen-Avatar', description: 'Detailliertes Kandidatenprofil', icon: 'logo-google-docs', type: 'output', x: 720, y: 58, demoConfig: { delay: 12000, artifacts: [{ type: 'url', label: 'Kandidatenprofil – Novacode', url: 'https://docs.google.com/document/d/1TOLqoqvEYy_DTxMb1zSUeq-cmXmNHmmUQe9EG2B1vEY/edit', contentPreview: 'Detailliertes Kandidatenprofil erstellt: Senior Developer, 28-40 Jahre, sucht Remote & moderne Stacks' }] } },
      { id: 'st04', label: 'Arbeitgeber-Avatar', description: 'Arbeitgeber-Positionierung', icon: 'logo-google-docs', type: 'output', x: 720, y: 198, demoConfig: { delay: 12000, artifacts: [{ type: 'url', label: 'Arbeitgeber-Strategie – Novacode', url: 'https://docs.google.com/document/d/1de1XU5ykeIw36kKSiorQqzPAGkHfsceflnTCBpVY26Q/edit', contentPreview: 'Arbeitgeber-Positionierung: Remote-First, moderner Stack, flache Hierarchien' }] } },
      { id: 'st05', label: 'Messaging-Matrix', description: 'Kern-Botschaften und Positionierung', icon: 'logo-google-docs', type: 'output', x: 720, y: 338, demoConfig: { delay: 10000, artifacts: [{ type: 'url', label: 'Messaging Matrix – Novacode', url: 'https://docs.google.com/document/d/1HLMrDn_p1aqL7nnfB09e0mPakj-m0BSIhQwTdkoX03E/edit', contentPreview: 'Messaging-Framework: Hauptbotschaft, USPs, Tonalität definiert' }] } },
      { id: 'st06', label: 'Creative Briefing', description: 'Formatvorgaben, Bildsprache, Mood', icon: 'logo-google-docs', type: 'output', x: 1060, y: 58, demoConfig: { delay: 8000, artifacts: [{ type: 'url', label: 'Creative Briefing – Novacode', url: 'https://docs.google.com/document/d/1sxB6R6l4DUn10hYEhY5xCEkNxZ4dvE9EUFvgT0hmCz8/edit', contentPreview: 'Formatvorgaben, Bildsprache, Farbschema, Mood-Board-Referenzen' }] } },
      { id: 'st07', label: 'Marken-Richtlinien', description: 'Logo, Farben, Fonts, Dos & Don\'ts', icon: 'logo-google-docs', type: 'output', x: 1060, y: 198, demoConfig: { delay: 8000, artifacts: [{ type: 'url', label: 'Arbeitgeber-Narrativ – Novacode', url: 'https://docs.google.com/document/d/1Xp0y_liDQ43AMdH3cjEwxdo9ZSZOP1AlVr8r-pn2Cps/edit', contentPreview: 'Kern-Narrativ: Bei Novacode baust du nicht nur Software — du gestaltest die Zukunft mit.' }] } },
      { id: 'st08', label: 'Zusammenführen', description: 'Alle Dokumente als Single Source of Truth', icon: 'git-merge', type: 'process', x: 1400, y: 198, demoConfig: { delay: 5000, artifacts: [{ type: 'text', label: 'Single Source of Truth', url: '#', contentPreview: 'Alle Dokumente als Single Source of Truth zusammengeführt' }] } },
      { id: 'st09', label: 'Strategie- & Marken-Review', description: 'Claudio: Strategie prüfen & freigeben', icon: 'shield-check', type: 'approval', x: 1740, y: 198, demoConfig: { delay: 8000, artifacts: [{ type: 'text', label: 'Strategie- & Marken-Review', url: '#', contentPreview: 'Strategie- & Marken-Review: Freigabe erteilt' }] } },
      { id: 'st10', label: 'Close: Strategie erstellt', description: 'Phase → Strategie erstellt', icon: 'logo-close', type: 'process', x: 2080, y: 198, demoConfig: { delay: 5000, artifacts: [{ type: 'url', label: 'Close CRM: Status aktualisiert', url: 'https://app.close.com/pipeline/pipe_2Zs3qMCbUuykBfzFT8qDdh/', contentPreview: 'Close CRM: Phase → Strategie erstellt' }] } },
    ],
    connections: [
      { from: 'st01', to: 'st02' },
      { from: 'st02', to: 'st03' }, { from: 'st02', to: 'st04' }, { from: 'st02', to: 'st05' },
      { from: 'st03', to: 'st06' }, { from: 'st04', to: 'st07' },
      { from: 'st05', to: 'st08' }, { from: 'st06', to: 'st08' }, { from: 'st07', to: 'st08' },
      { from: 'st08', to: 'st09' },
      { from: 'st09', to: 'st10' },
    ],
    groups: [
      { id: 'gst1', label: 'KI-Analyse', x: 15, y: 178, width: 620, height: 148, color: 'purple' },
      { id: 'gst2', label: 'Strategische Dokumente', x: 695, y: 0, width: 620, height: 408, color: 'purple' },
      { id: 'gst3', label: 'Qualitätssicherung', x: 1375, y: 138, width: 960, height: 148, color: 'green' },
    ],
    outputs: [],
    executionCount: 0,
  },

  // ── 0d. Text-Erstellung (Sub-System) ──────────────────────────────────────
  {
    id: 'demo-novacode-copy',
    user_id: 'local-user',
    isDemo: true,
    parentId: 'demo-novacode',
    subSystemOrder: 3,
    name: 'Text-Erstellung',
    description: 'Landingpage-Texte, Anzeigentexte und Variationen generieren, Text-Review durchführen.',
    category: 'Recruiting',
    icon: 'file-text',
    status: 'active',
    webhookUrl: '',
    nodes: [
      { id: 'cc01', label: 'KI: Landingpage-Texte', description: 'LP, Formular, Danke-Seite Texte', icon: 'logo-claude', type: 'ai', x: 40, y: 118, demoConfig: { delay: 25000, artifacts: [{ type: 'url', label: 'Landingpage-Texte – Novacode', url: 'https://docs.google.com/document/d/1CEZAzrioyaqn7PMfc0ARadG1Jw5ic-uXTV4tE1aX2PU/edit', contentPreview: 'Hero, Benefits, Team, Testimonials, CTA-Texte generiert' }, { type: 'url', label: 'Formularseite-Texte – Novacode', url: 'https://docs.google.com/document/d/1Qe0zXGHVcABIEMTZUn4tMttloGfa14bpCtKU3L95-Qw/edit', contentPreview: 'Formular-Labels, Validierungstexte, Datenschutz-Hinweis' }, { type: 'url', label: 'Dankeseite-Texte – Novacode', url: 'https://docs.google.com/document/d/13M6owsnBTr6OAElN0LvhF5Oz_Ky4l0OdvhSb2dhfQ7g/edit', contentPreview: 'Bestätigungstext, nächste Schritte, Social Proof' }] } },
      { id: 'cc02', label: 'KI: Anzeigentexte', description: 'Haupttext, Überschriften, Beschreibungen', icon: 'logo-claude', type: 'ai', x: 40, y: 298, demoConfig: { delay: 18000, artifacts: [{ type: 'url', label: 'Anzeigen-Texte – Novacode', url: 'https://docs.google.com/document/d/1lf2U2ZI47-Oz8eTW8OKziGwN_Z_SAssS8DiJAiiJ5SQ/edit', contentPreview: 'Haupttexte, Überschriften, Beschreibungen generiert' }, { type: 'url', label: 'Videoskript – Novacode', url: 'https://docs.google.com/document/d/171Eg7V8jKGOYrqdYOLUM6DvfDodet_mxPrUB5DmMqEs/edit', contentPreview: 'Recruiting-Video 60s: Hook → Problem → Lösung → CTA' }] } },
      { id: 'cc03', label: 'Variationen', description: '3 Winkel, verschiedene Hooks', icon: 'logo-google-docs', type: 'output', x: 380, y: 298, demoConfig: { delay: 8000, artifacts: [{ type: 'url', label: 'Anzeigen-Variationen – Novacode', url: 'https://docs.google.com/document/d/1ITRWWBL9tY-2AUi4CIB6wbPqbk6CGcv5UB6ePtH87j0/edit', contentPreview: 'Retargeting + Warmup Variationen: 3 Winkel, verschiedene Hooks' }] } },
      { id: 'cc04', label: 'Text-Review', description: 'Claudio: Texte prüfen & freigeben', icon: 'shield-check', type: 'approval', x: 720, y: 198, demoConfig: { delay: 8000, artifacts: [{ type: 'text', label: 'Text-Review', url: '#', contentPreview: 'Text-Review: Freigabe erteilt' }] } },
      { id: 'cc05', label: 'Close: Assets erstellt', description: 'Phase → Assets erstellt', icon: 'logo-close', type: 'process', x: 1060, y: 198, demoConfig: { delay: 5000, artifacts: [{ type: 'url', label: 'Close CRM: Status aktualisiert', url: 'https://app.close.com/pipeline/pipe_2Zs3qMCbUuykBfzFT8qDdh/', contentPreview: 'Close CRM: Phase → Assets erstellt' }] } },
    ],
    connections: [
      { from: 'cc01', to: 'cc04' },
      { from: 'cc02', to: 'cc03' },
      { from: 'cc03', to: 'cc04' },
      { from: 'cc04', to: 'cc05' },
    ],
    groups: [
      { id: 'gcc1', label: 'KI-Generierung', x: 15, y: 58, width: 280, height: 308, color: 'purple' },
      { id: 'gcc2', label: 'Review', x: 695, y: 138, width: 620, height: 148, color: 'green' },
    ],
    outputs: [],
    executionCount: 0,
  },

  // ── 0e. Funnel, Pixel & Tracking (Sub-System) ────────────────────────────
  {
    id: 'demo-novacode-funnel',
    user_id: 'local-user',
    isDemo: true,
    parentId: 'demo-novacode',
    subSystemOrder: 4,
    name: 'Funnel, Pixel & Tracking',
    description: 'Website-Template auswählen, Copy einsetzen, 5 Seiten bauen, Meta Pixel und Tracking Events konfigurieren.',
    category: 'Recruiting',
    icon: 'globe',
    status: 'active',
    webhookUrl: '',
    nodes: [
      { id: 'fn01', label: 'Template auswählen', description: 'Recruiting Pro Template selektieren', icon: 'layout', type: 'process', x: 40, y: 198, demoConfig: { delay: 5000, artifacts: [{ type: 'text', label: 'Template ausgewählt', url: '#', contentPreview: 'Template "Recruiting Pro" selektiert: Hero, Benefits, Team, Formular' }] } },
      { id: 'fn02', label: 'Copy einsetzen', description: 'Generierte Texte in Template einsetzen', icon: 'text-cursor-input', type: 'process', x: 380, y: 198, demoConfig: { delay: 8000, artifacts: [{ type: 'text', label: 'Copy eingesetzt', url: '#', contentPreview: 'Alle generierten Texte in Template eingesetzt: Hero, Benefits, CTAs' }] } },
      { id: 'fn03', label: 'Bilder vorbereiten', description: 'Logo, Teamfotos, OG-Image', icon: 'image', type: 'process', x: 380, y: 358, demoConfig: { delay: 10000, artifacts: [{ type: 'text', label: 'Bilder vorbereitet', url: '#', contentPreview: 'Logo optimiert, Teamfotos zugeschnitten, OG-Image generiert' }] } },
      { id: 'fn04', label: 'Design anpassen', description: 'Brand Colors, Fonts, Layout', icon: 'palette', type: 'process', x: 720, y: 198, demoConfig: { delay: 15000, artifacts: [{ type: 'text', label: 'Design angepasst', url: '#', contentPreview: 'Brand Colors, Fonts und Layout an Novacode CI angepasst' }] } },
      { id: 'fn05', label: 'Website bauen', description: '5 Seiten zusammenfügen & deployen', icon: 'globe', type: 'process', x: 1060, y: 198, demoConfig: { delay: 45000, artifacts: [{ type: 'text', label: 'Website gebaut & deployed', url: '#', contentPreview: 'Alle Seiten zusammengefügt und auf Vercel deployed' }] } },
      { id: 'fn06', label: 'Landingpage', description: 'Hauptseite live', icon: 'globe', type: 'output', x: 1400, y: 18, demoConfig: { delay: 3000, artifacts: [{ type: 'url', label: 'Landingpage – Novacode', url: 'https://demo-recruiting.vercel.app/demo-landing/', contentPreview: 'Landingpage live auf Vercel' }] } },
      { id: 'fn07', label: 'Bewerbungsseite', description: 'Bewerbungsformular', icon: 'globe', type: 'output', x: 1400, y: 158, demoConfig: { delay: 3000, artifacts: [{ type: 'url', label: 'Bewerbungsformular – Novacode', url: 'https://demo-recruiting.vercel.app/demo-formular', contentPreview: 'Bewerbungsformular live auf Vercel' }] } },
      { id: 'fn08', label: 'Dankeseite', description: 'Bestätigungsseite', icon: 'globe', type: 'output', x: 1400, y: 298, demoConfig: { delay: 3000, artifacts: [{ type: 'url', label: 'Dankeseite – Novacode', url: 'https://demo-recruiting.vercel.app/demo-danke', contentPreview: 'Bestätigungsseite live auf Vercel' }] } },
      { id: 'fn09', label: 'Datenschutz & Impressum', description: 'Datenschutz & Impressum', icon: 'shield', type: 'output', x: 1400, y: 438, demoConfig: { delay: 3000, artifacts: [{ type: 'text', label: 'Datenschutz & Impressum', url: '#', contentPreview: 'Datenschutz & Impressum live' }] } },
      { id: 'fn10', label: 'Pixel- & Event-Setup', description: 'Meta Pixel + ViewContent, AddToCart, Lead', icon: 'target', type: 'process', x: 1740, y: 118, demoConfig: { delay: 10000, artifacts: [{ type: 'text', label: 'Meta Pixel installiert', url: '#', contentPreview: 'Meta Pixel installiert, Events: ViewContent, AddToCart, Lead konfiguriert' }] } },
      { id: 'fn11', label: 'Funnel- & Pixel-Review', description: 'Anak: Alle Seiten + Tracking prüfen', icon: 'shield-check', type: 'approval', x: 1740, y: 298, demoConfig: { delay: 8000, artifacts: [{ type: 'text', label: 'Funnel- & Pixel-Review', url: '#', contentPreview: 'Funnel- & Pixel-Review: Freigabe erteilt' }] } },
    ],
    connections: [
      { from: 'fn01', to: 'fn02' },
      { from: 'fn03', to: 'fn04' },
      { from: 'fn02', to: 'fn04' },
      { from: 'fn04', to: 'fn05' },
      { from: 'fn05', to: 'fn06' }, { from: 'fn05', to: 'fn07' }, { from: 'fn05', to: 'fn08' }, { from: 'fn05', to: 'fn09' },
      { from: 'fn06', to: 'fn10' },
      { from: 'fn07', to: 'fn10' },
      { from: 'fn08', to: 'fn10' },
      { from: 'fn10', to: 'fn11' },
      { from: 'fn09', to: 'fn11' },
    ],
    groups: [
      { id: 'gfn1', label: 'Website-Erstellung', x: 15, y: 138, width: 960, height: 288, color: 'blue' },
      { id: 'gfn2', label: 'Seiten', x: 1375, y: 0, width: 280, height: 510, color: 'blue' },
      { id: 'gfn3', label: 'Tracking & QA', x: 1715, y: 58, width: 280, height: 308, color: 'green' },
    ],
    outputs: [],
    executionCount: 0,
  },

  // ── 0f. Zielgruppen & Kampagnen-Setup (Sub-System) ────────────────────────
  {
    id: 'demo-novacode-campaigns',
    user_id: 'local-user',
    isDemo: true,
    parentId: 'demo-novacode',
    subSystemOrder: 5,
    name: 'Zielgruppen & Kampagnen-Setup',
    description: 'Zielgruppen erstellen, 3 Kampagnen (Kaltakquise, Retargeting, Warmup) mit Anzeigengruppen und Ads konfigurieren.',
    category: 'Recruiting',
    icon: 'target',
    status: 'active',
    webhookUrl: '',
    nodes: [
      { id: 'ca01', label: 'Meta: Alle Besucher', description: 'Custom Audience: Website-Besucher der letzten 30 Tage', icon: 'logo-meta', type: 'process', x: 40, y: 18, demoConfig: { delay: 6000, artifacts: [{ type: 'url', label: 'Custom Audience erstellt', url: 'https://adsmanager.facebook.com/adsmanager/manage/audiences?act=1282595205992969', contentPreview: 'Custom Audience: AllVisitors_30d erstellt' }] } },
      { id: 'ca02', label: 'Meta: LP ohne Bewerbung', description: 'Custom Audience: LP-Besucher ohne Bewerbung (7 Tage)', icon: 'logo-meta', type: 'process', x: 40, y: 178, demoConfig: { delay: 6000, artifacts: [{ type: 'url', label: 'Custom Audience erstellt', url: 'https://adsmanager.facebook.com/adsmanager/manage/audiences?act=1282595205992969', contentPreview: 'Custom Audience: LP_Visitors_NoApplication_7d erstellt' }] } },
      { id: 'ca03', label: 'Meta: Formular ohne Lead', description: 'Custom Audience: Formular-Besucher ohne Abschluss (7 Tage)', icon: 'logo-meta', type: 'process', x: 40, y: 338, demoConfig: { delay: 6000, artifacts: [{ type: 'url', label: 'Custom Audience erstellt', url: 'https://adsmanager.facebook.com/adsmanager/manage/audiences?act=1282595205992969', contentPreview: 'Custom Audience: Application_Visitors_NoLead_7d erstellt' }] } },
      { id: 'ca04', label: 'Meta: Initial-Kampagne', description: 'Neue Zielgruppen ansprechen — Objective: Leads', icon: 'logo-meta', type: 'process', x: 380, y: 18, demoConfig: { delay: 8000, artifacts: [{ type: 'url', label: 'Initial-Kampagne erstellt', url: 'https://adsmanager.facebook.com/adsmanager/manage/campaigns?act=1282595205992969', contentPreview: 'Kampagne Initial_Novacode GmbH_Recruiting_Leads erstellt, Objective: Leads' }] } },
      { id: 'ca05', label: 'Meta: Initial Ad Sets', description: 'Broad + Interest Targeting, je 30\u20AC/Tag', icon: 'logo-meta', type: 'process', x: 720, y: 18, demoConfig: { delay: 12000, artifacts: [{ type: 'url', label: 'Initial Ad Sets erstellt', url: 'https://adsmanager.facebook.com/adsmanager/manage/campaigns?act=1282595205992969', contentPreview: '3 Anzeigengruppen: DE_Broad, DE_Interest_Recruiting, DE_Interest_Management (je 30\u20AC/Tag)' }] } },
      { id: 'ca06', label: 'Meta: Retargeting-Kampagne', description: 'Besucher erneut ansprechen — Objective: Leads', icon: 'logo-meta', type: 'process', x: 380, y: 178, demoConfig: { delay: 8000, artifacts: [{ type: 'url', label: 'Retargeting-Kampagne erstellt', url: 'https://adsmanager.facebook.com/adsmanager/manage/campaigns?act=1282595205992969', contentPreview: 'Kampagne Retargeting_Novacode GmbH_Recruiting_Leads erstellt' }] } },
      { id: 'ca07', label: 'Meta: Retargeting Ad Sets', description: 'Alle Besucher + LP ohne Bewerbung + Formular ohne Lead', icon: 'logo-meta', type: 'process', x: 720, y: 178, demoConfig: { delay: 12000, artifacts: [{ type: 'url', label: 'Retargeting Ad Sets erstellt', url: 'https://adsmanager.facebook.com/adsmanager/manage/campaigns?act=1282595205992969', contentPreview: '3 Retargeting-Anzeigengruppen: DE_RT_AllVisitors_30d, DE_RT_LP_NoApplication_7d, DE_RT_Application_NoLead_7d' }] } },
      { id: 'ca08', label: 'Meta: Warmup-Kampagne', description: 'Video Views für Markenbekanntheit', icon: 'logo-meta', type: 'process', x: 380, y: 338, demoConfig: { delay: 7000, artifacts: [{ type: 'url', label: 'Warmup-Kampagne erstellt', url: 'https://adsmanager.facebook.com/adsmanager/manage/campaigns?act=1282595205992969', contentPreview: 'Kampagne Warmup_Novacode GmbH_Recruiting_Views erstellt, Objective: Video Views' }] } },
      { id: 'ca09', label: 'Meta: Warmup Ad Sets', description: 'Video Views in Feeds, Stories & Reels', icon: 'logo-meta', type: 'process', x: 720, y: 338, demoConfig: { delay: 10000, artifacts: [{ type: 'url', label: 'Warmup Ad Sets erstellt', url: 'https://adsmanager.facebook.com/adsmanager/manage/campaigns?act=1282595205992969', contentPreview: 'Warmup-Anzeigengruppen: DE_Warmup_Views_30d' }] } },
      { id: 'ca10', label: 'Zielgruppen & Pixel QA', description: 'Claudio: Zielgruppen verifizieren', icon: 'shield-check', type: 'approval', x: 1060, y: 118, demoConfig: { delay: 8000, artifacts: [{ type: 'url', label: 'Zielgruppen & Pixel QA', url: 'https://adsmanager.facebook.com/adsmanager/manage/audiences?act=1282595205992969', contentPreview: 'Zielgruppen & Pixel QA: Alle Zielgruppen verifiziert' }] } },
      { id: 'ca11', label: 'Kampagnen-Review', description: 'Claudio: Alle Kampagnen prüfen', icon: 'shield-check', type: 'approval', x: 1060, y: 278, demoConfig: { delay: 8000, artifacts: [{ type: 'url', label: 'Kampagnen-Review', url: 'https://adsmanager.facebook.com/adsmanager/manage/campaigns?act=1282595205992969&business_id=191333547045260&global_scope_id=191333547045260', contentPreview: 'Kampagnen-Review: Alle 3 Kampagnen geprüft und freigegeben' }] } },
    ],
    connections: [
      { from: 'ca01', to: 'ca04' }, { from: 'ca02', to: 'ca06' }, { from: 'ca03', to: 'ca08' },
      { from: 'ca04', to: 'ca05' }, { from: 'ca06', to: 'ca07' }, { from: 'ca08', to: 'ca09' },
      { from: 'ca05', to: 'ca10' }, { from: 'ca07', to: 'ca10' },
      { from: 'ca09', to: 'ca11' },
      { from: 'ca10', to: 'ca11' },
    ],
    groups: [
      { id: 'gca1', label: 'Zielgruppen', x: 15, y: 0, width: 280, height: 408, color: 'blue' },
      { id: 'gca2', label: 'Kampagnen & Anzeigengruppen', x: 355, y: 0, width: 620, height: 408, color: 'purple' },
      { id: 'gca3', label: 'QA', x: 1035, y: 58, width: 280, height: 288, color: 'green' },
    ],
    outputs: [],
    executionCount: 0,
  },

  // ── 0g. Prüfung & Go-Live (Sub-System) ────────────────────────────────────
  {
    id: 'demo-novacode-launch',
    user_id: 'local-user',
    isDemo: true,
    parentId: 'demo-novacode',
    subSystemOrder: 6,
    name: 'Prüfung & Go-Live',
    description: 'Alle Review-Tasks prüfen, finale Freigabe, Kampagnen aktivieren, Go-Live und Performance-Dashboard.',
    category: 'Recruiting',
    icon: 'rocket',
    status: 'active',
    webhookUrl: '',
    nodes: [
      { id: 'rl01', label: 'Strategie-Review ✓', description: 'Bestätigt', icon: 'check-circle', type: 'process', x: 40, y: 18, demoConfig: { delay: 3000, artifacts: [{ type: 'text', label: 'Strategie-Review bestätigt', url: '#', contentPreview: 'Strategie-Review: Bestätigt' }] } },
      { id: 'rl02', label: 'Text-Review ✓', description: 'Bestätigt', icon: 'check-circle', type: 'process', x: 40, y: 138, demoConfig: { delay: 3000, artifacts: [{ type: 'text', label: 'Text-Review bestätigt', url: '#', contentPreview: 'Text-Review: Bestätigt' }] } },
      { id: 'rl03', label: 'Funnel-Review ✓', description: 'Bestätigt', icon: 'check-circle', type: 'process', x: 40, y: 258, demoConfig: { delay: 3000, artifacts: [{ type: 'text', label: 'Funnel-Review bestätigt', url: '#', contentPreview: 'Funnel-Review: Bestätigt' }] } },
      { id: 'rl04', label: 'Zielgruppen-QA ✓', description: 'Bestätigt', icon: 'check-circle', type: 'process', x: 40, y: 378, demoConfig: { delay: 3000, artifacts: [{ type: 'text', label: 'Zielgruppen-QA bestätigt', url: '#', contentPreview: 'Zielgruppen-QA: Bestätigt' }] } },
      { id: 'rl05', label: 'Kampagnen-Review ✓', description: 'Bestätigt', icon: 'check-circle', type: 'process', x: 40, y: 498, demoConfig: { delay: 3000, artifacts: [{ type: 'text', label: 'Kampagnen-Review bestätigt', url: '#', contentPreview: 'Kampagnen-Review: Bestätigt' }] } },
      { id: 'rl06', label: 'Slack: Assets bereit', description: 'Nachricht mit allen Links', icon: 'logo-slack', type: 'output', x: 380, y: 118, demoConfig: { delay: 5000, artifacts: [{ type: 'url', label: 'Slack: Assets bereit', url: 'https://app.slack.com/', contentPreview: 'Slack: Alle Assets für Novacode bereit — Links gesendet' }] } },
      { id: 'rl07', label: 'Close: Warte auf Freigabe', description: 'Phase → Warte auf Freigabe', icon: 'logo-close', type: 'process', x: 380, y: 298, demoConfig: { delay: 5000, artifacts: [{ type: 'url', label: 'Close CRM: Status aktualisiert', url: 'https://app.close.com/pipeline/pipe_2Zs3qMCbUuykBfzFT8qDdh/', contentPreview: 'Close CRM: Phase → Warte auf Freigabe' }] } },
      { id: 'rl08', label: 'Finale Freigabe', description: 'Internes Go', icon: 'shield-check', type: 'approval', x: 720, y: 198, demoConfig: { delay: 10000, artifacts: [{ type: 'text', label: 'Finale Freigabe', url: '#', contentPreview: 'Finale Freigabe: Internes Go erteilt' }] } },
      { id: 'rl09', label: 'Close: Bereit für Launch', description: 'Phase → Bereit für Launch', icon: 'logo-close', type: 'process', x: 1060, y: 198, demoConfig: { delay: 5000, artifacts: [{ type: 'url', label: 'Close CRM: Status aktualisiert', url: 'https://app.close.com/pipeline/pipe_2Zs3qMCbUuykBfzFT8qDdh/', contentPreview: 'Close CRM: Phase → Bereit für Launch' }] } },
      { id: 'rl10', label: 'Kampagnen aktivieren', description: 'Status → Aktiv in Meta', icon: 'logo-meta', type: 'process', x: 1400, y: 198, demoConfig: { delay: 8000, artifacts: [{ type: 'url', label: 'Meta Ads: Kampagnen aktiv', url: 'https://adsmanager.facebook.com/adsmanager/manage/campaigns?act=1282595205992969&business_id=191333547045260&global_scope_id=191333547045260', contentPreview: 'Kampagnen-Status → Aktiv' }] } },
      { id: 'rl11', label: 'Close: Live', description: 'Phase → Live', icon: 'logo-close', type: 'process', x: 1740, y: 118, demoConfig: { delay: 5000, artifacts: [{ type: 'url', label: 'Close CRM: Live', url: 'https://app.close.com/pipeline/pipe_2Zs3qMCbUuykBfzFT8qDdh/', contentPreview: 'Close CRM: Phase → Live, Automations-Status → Live' }] } },
      { id: 'rl12', label: 'Slack: Wir sind live', description: 'Live-Nachricht mit Datum und KPIs', icon: 'logo-slack', type: 'output', x: 1740, y: 298, demoConfig: { delay: 4000, artifacts: [{ type: 'url', label: 'Slack: Live-Benachrichtigung', url: 'https://app.slack.com/', contentPreview: 'Slack: Novacode Recruiting ist LIVE!' }] } },
      { id: 'rl13', label: 'Dashboard', description: 'Recruiting-Dashboard URL', icon: 'bar-chart', type: 'output', x: 2080, y: 198, demoConfig: { delay: 3000, artifacts: [{ type: 'url', label: 'Recruiting-Dashboard – Novacode', url: 'https://demo-recruiting.vercel.app/recruiting', contentPreview: 'Live-Dashboard mit KPIs und Performance-Daten' }] } },
    ],
    connections: [
      { from: 'rl01', to: 'rl06' }, { from: 'rl02', to: 'rl06' }, { from: 'rl03', to: 'rl06' },
      { from: 'rl04', to: 'rl07' }, { from: 'rl05', to: 'rl07' },
      { from: 'rl06', to: 'rl08' }, { from: 'rl07', to: 'rl08' },
      { from: 'rl08', to: 'rl09' },
      { from: 'rl09', to: 'rl10' },
      { from: 'rl10', to: 'rl11' },
      { from: 'rl10', to: 'rl12' },
      { from: 'rl11', to: 'rl13' },
      { from: 'rl12', to: 'rl13' },
    ],
    groups: [
      { id: 'grl1', label: 'Review-Status', x: 15, y: 0, width: 280, height: 568, color: 'orange' },
      { id: 'grl2', label: 'Freigabe', x: 355, y: 58, width: 620, height: 308, color: 'green' },
      { id: 'grl3', label: 'Go-Live', x: 1035, y: 58, width: 1300, height: 308, color: 'green' },
    ],
    outputs: [],
    executionCount: 0,
  },
]

// ── Workflow Templates ─────────────────────────────────────────────────────

export const DEMO_TEMPLATES: WorkflowTemplate[] = []
const _UNUSED_TEMPLATES: WorkflowTemplate[] = [
  // ── 1. Lead Generation & Nurturing ───────────────────────────────────────
  {
    id: 'tpl-lead-gen',
    user_id: 'local-user',
    name: 'Lead Generation & Nurturing',
    description:
      'Capture leads from multiple channels, score them with AI, and nurture with automated email sequences.',
    category: 'Marketing',
    icon: 'target',
    nodeCount: 8,
    tags: ['leads', 'email', 'AI scoring', 'CRM'],
    nodes: [
      { id: 't1', label: 'Form Submission', description: 'Website form captured', icon: 'logo-zapier', type: 'trigger', ...p(0, 0) },
      { id: 't2', label: 'LinkedIn Ad', description: 'Lead ad conversion', icon: 'logo-linkedin', type: 'trigger', ...p(0, 1) },
      { id: 't3', label: 'Merge & Dedupe', description: 'Combine and clean leads', icon: 'database', type: 'process', ...p(1, 0) },
      { id: 't4', label: 'AI Lead Scoring', description: 'Score based on ICP fit', icon: 'logo-openai', type: 'ai', ...p(2, 0) },
      { id: 't5', label: 'Segment & Route', description: 'High/medium/low buckets', icon: 'split', type: 'process', ...p(3, 0) },
      { id: 't6', label: 'CRM Update', description: 'Create or update in CRM', icon: 'logo-hubspot', type: 'output', ...p(4, 0) },
      { id: 't7', label: 'Email Sequence', description: 'Nurture email drip', icon: 'logo-gmail', type: 'output', ...p(4, 1) },
      { id: 't8', label: 'Slack Alert', description: 'Notify sales team', icon: 'logo-slack', type: 'output', ...p(4, 2) },
    ],
    connections: [
      { from: 't1', to: 't3' },
      { from: 't2', to: 't3' },
      { from: 't3', to: 't4' },
      { from: 't4', to: 't5' },
      { from: 't5', to: 't6' },
      { from: 't5', to: 't7' },
      { from: 't5', to: 't8' },
    ],
    groups: [
      { id: 'tg1', label: 'Capture', x: 15, y: 8, width: 280, height: 256, color: 'blue' },
      { id: 'tg2', label: 'Scoring', x: 355, y: 8, width: 620, height: 148, color: 'purple' },
      { id: 'tg3', label: 'Activation', x: 1035, y: 8, width: 280, height: 364, color: 'green' },
    ],
  },

  // ── 2. Content Production Pipeline ───────────────────────────────────────
  {
    id: 'tpl-content-prod',
    user_id: 'local-user',
    name: 'Content Production Pipeline',
    description:
      'Research, draft, and distribute content across blog, social, and email from a single brief.',
    category: 'Marketing',
    icon: 'type',
    nodeCount: 7,
    tags: ['content', 'blog', 'social media', 'AI writing'],
    nodes: [
      { id: 't1', label: 'Content Brief', description: 'Topic and keywords', icon: 'clipboard', type: 'trigger', ...p(0, 0) },
      { id: 't2', label: 'Research Agent', description: 'Gather sources and data', icon: 'logo-openai', type: 'ai', ...p(1, 0) },
      { id: 't3', label: 'Draft Generator', description: 'Create long-form draft', icon: 'logo-claude', type: 'ai', ...p(2, 0) },
      { id: 't4', label: 'Blog Post', description: 'Publish to CMS', icon: 'logo-wordpress', type: 'output', ...p(3, 0) },
      { id: 't5', label: 'Social Posts', description: 'Adapt for channels', icon: 'logo-meta', type: 'output', ...p(3, 1) },
      { id: 't6', label: 'Newsletter', description: 'Add to email blast', icon: 'logo-gmail', type: 'output', ...p(3, 2) },
      { id: 't7', label: 'Analytics Tag', description: 'Track performance', icon: 'logo-google-analytics', type: 'output', ...p(4, 0) },
    ],
    connections: [
      { from: 't1', to: 't2' },
      { from: 't2', to: 't3' },
      { from: 't3', to: 't4' },
      { from: 't3', to: 't5' },
      { from: 't3', to: 't6' },
      { from: 't4', to: 't7' },
    ],
  },

  // ── 3. Client Reporting Automation ───────────────────────────────────────
  {
    id: 'tpl-client-report',
    user_id: 'local-user',
    name: 'Client Reporting Automation',
    description:
      'Pull metrics from ad platforms and analytics, generate AI summaries, and deliver polished client reports.',
    category: 'Operations',
    icon: 'bar-chart',
    nodeCount: 6,
    tags: ['reporting', 'analytics', 'PDF', 'clients'],
    nodes: [
      { id: 't1', label: 'Scheduled Trigger', description: 'Monthly cadence', icon: 'timer', type: 'trigger', ...p(0, 0) },
      { id: 't2', label: 'Pull Metrics', description: 'Ads + Analytics data', icon: 'logo-google-analytics', type: 'process', ...p(1, 0) },
      { id: 't3', label: 'AI Summary', description: 'Generate insights', icon: 'logo-openai', type: 'ai', ...p(2, 0) },
      { id: 't4', label: 'Build Report', description: 'Format in template', icon: 'logo-google-docs', type: 'process', ...p(3, 0) },
      { id: 't5', label: 'Save to Drive', description: 'Archive as PDF', icon: 'logo-google-drive', type: 'output', ...p(4, 0) },
      { id: 't6', label: 'Send to Client', description: 'Email with attachment', icon: 'logo-gmail', type: 'output', ...p(4, 1) },
    ],
    connections: [
      { from: 't1', to: 't2' },
      { from: 't2', to: 't3' },
      { from: 't3', to: 't4' },
      { from: 't4', to: 't5' },
      { from: 't4', to: 't6' },
    ],
  },

  // ── 4. Marketing Agency Fulfillment ──────────────────────────────────────
  {
    id: 'tpl-agency',
    user_id: 'local-user',
    name: 'Marketing Agency Fulfillment',
    description:
      'End-to-end client fulfillment: onboarding, content, ads, and reporting in a single workflow.',
    category: 'Operations',
    icon: 'workflow',
    nodeCount: 9,
    tags: ['agency', 'onboarding', 'ads', 'reporting', 'full-service'],
    nodes: [
      { id: 't1', label: 'New Client', description: 'Onboarding form submitted', icon: 'users', type: 'trigger', ...p(0, 0) },
      { id: 't2', label: 'AI Briefing', description: 'Extract strategy from call', icon: 'logo-openai', type: 'ai', ...p(1, 0) },
      { id: 't3', label: 'Generate Website', description: 'Build landing page', icon: 'globe', type: 'process', ...p(2, 0) },
      { id: 't4', label: 'Write Ad Copy', description: 'Create campaign text', icon: 'logo-claude', type: 'ai', ...p(2, 1) },
      { id: 't5', label: 'Setup Google Ads', description: 'Configure campaigns', icon: 'logo-google-ads', type: 'output', ...p(3, 0) },
      { id: 't6', label: 'Setup Meta Ads', description: 'Facebook & Instagram', icon: 'logo-meta', type: 'output', ...p(3, 1) },
      { id: 't7', label: 'Tracking Setup', description: 'Analytics & pixels', icon: 'logo-google-analytics', type: 'process', ...p(3, 2) },
      { id: 't8', label: 'Client Dashboard', description: 'Real-time metrics', icon: 'bar-chart', type: 'output', ...p(4, 1) },
      { id: 't9', label: 'Welcome Email', description: 'Credentials & timeline', icon: 'logo-gmail', type: 'output', ...p(4, 0) },
    ],
    connections: [
      { from: 't1', to: 't2' },
      { from: 't2', to: 't3' },
      { from: 't2', to: 't4' },
      { from: 't3', to: 't5' },
      { from: 't4', to: 't5' },
      { from: 't4', to: 't6' },
      { from: 't5', to: 't7' },
      { from: 't6', to: 't7' },
      { from: 't7', to: 't8' },
      { from: 't3', to: 't9' },
    ],
    groups: [
      { id: 'tg1', label: 'Onboarding', x: 15, y: 8, width: 280, height: 148, color: 'blue' },
      { id: 'tg2', label: 'Production', x: 355, y: 8, width: 620, height: 256, color: 'purple' },
      { id: 'tg3', label: 'Launch & Monitor', x: 1035, y: 8, width: 280, height: 256, color: 'green' },
    ],
  },

  // ── 5. Recruiting Fulfillment ──────────────────────────────────────────────
  {
    id: 'tpl-recruiting',
    user_id: 'local-user',
    name: 'Recruiting Fulfillment',
    description: 'Vom Kickoff-Call über Knowledge Processing und Content-Produktion bis zum Launch mit Performance-Tracking.',
    category: 'Recruiting',
    icon: 'building-2',
    nodeCount: 12,
    tags: ['recruiting', 'agentur', 'fulfillment', 'KI'],
    nodes: [
      { id: 'rc1', label: 'Client Handover', description: 'Formular von Sales', icon: 'clipboard-check', type: 'trigger', ...p(0, 0) },
      { id: 'rc2', label: 'CRM Setup', description: 'Pipeline & Tags anlegen', icon: 'logo-hubspot', type: 'process', ...p(1, 0) },
      { id: 'rc3', label: 'Onboarding Call', description: 'Standardisiertes Gespräch', icon: 'video', type: 'process', ...p(2, 0) },
      { id: 'rc4', label: 'KI-Transkription', description: 'Call transkribieren & analysieren', icon: 'logo-openai', type: 'ai', ...p(3, 0) },
      { id: 'rc5', label: 'Daten extrahieren', description: 'Pain Points, Benefits, Messaging', icon: 'logo-claude', type: 'ai', ...p(4, 0) },
      { id: 'rc6', label: 'Website Copy', description: 'Landing Page Texte generieren', icon: 'logo-claude', type: 'ai', ...p(5, 0) },
      { id: 'rc7', label: 'Ad Copy', description: 'Meta & Google Anzeigentexte', icon: 'logo-claude', type: 'ai', ...p(5, 1) },
      { id: 'rc8', label: 'Website bauen', description: 'Template + Copy → Live', icon: 'globe', type: 'process', ...p(6, 0) },
      { id: 'rc9', label: 'Kampagnen Setup', description: 'Ads vorbereiten & starten', icon: 'logo-meta', type: 'output', ...p(6, 1) },
      { id: 'rc10', label: 'Review & Freigabe', description: 'Qualitätsprüfung', icon: 'shield-check', type: 'process', ...p(7, 0) },
      { id: 'rc11', label: 'Go Live', description: 'Alles live schalten', icon: 'rocket', type: 'output', ...p(8, 0) },
      { id: 'rc12', label: 'Performance Tracking', description: 'KPIs überwachen', icon: 'bar-chart', type: 'output', ...p(8, 1) },
    ],
    connections: [
      { from: 'rc1', to: 'rc2' },
      { from: 'rc2', to: 'rc3' },
      { from: 'rc3', to: 'rc4' },
      { from: 'rc4', to: 'rc5' },
      { from: 'rc5', to: 'rc6' }, { from: 'rc5', to: 'rc7' },
      { from: 'rc6', to: 'rc8' }, { from: 'rc7', to: 'rc9' },
      { from: 'rc8', to: 'rc10' }, { from: 'rc9', to: 'rc10' },
      { from: 'rc10', to: 'rc11' }, { from: 'rc10', to: 'rc12' },
    ],
    groups: [
      { id: 'trg1', label: 'Onboarding', x: 15, y: 8, width: 620, height: 148, color: 'blue' },
      { id: 'trg2', label: 'Knowledge Processing', x: 695, y: 8, width: 620, height: 148, color: 'purple' },
      { id: 'trg3', label: 'Produktion', x: 1375, y: 8, width: 620, height: 256, color: 'green' },
      { id: 'trg4', label: 'Launch & Tracking', x: 2055, y: 8, width: 620, height: 256, color: 'orange' },
    ],
  },

  // ── 6. Buchhaltung & Rechnungen ────────────────────────────────────────────
  {
    id: 'tpl-buchhaltung',
    user_id: 'local-user',
    name: 'Buchhaltung & Rechnungen',
    description: 'Eingangsrechnungen erfassen, Ausgangsrechnungen erstellen, Mahnwesen und Monatsabschluss automatisieren.',
    category: 'Operations',
    icon: 'receipt',
    nodeCount: 10,
    tags: ['buchhaltung', 'rechnungen', 'mahnwesen', 'finanzen'],
    nodes: [
      { id: 'bk1', label: 'Rechnung eingehend', description: 'PDF per Mail oder Upload', icon: 'logo-gmail', type: 'trigger', ...p(0, 0) },
      { id: 'bk2', label: 'KI-Extraktion', description: 'Betrag, Datum, Lieferant extrahieren', icon: 'logo-openai', type: 'ai', ...p(1, 0) },
      { id: 'bk3', label: 'Buchhaltung buchen', description: 'Automatisch kontieren', icon: 'database', type: 'process', ...p(2, 0) },
      { id: 'bk4', label: 'Freigabe anfordern', description: 'Manager muss bestätigen', icon: 'shield-check', type: 'process', ...p(3, 0) },
      { id: 'bk5', label: 'Zahlung auslösen', description: 'Überweisung vorbereiten', icon: 'logo-stripe', type: 'output', ...p(4, 0) },
      { id: 'bk6', label: 'Ausgangsrechnung', description: 'Rechnung aus Vorlage erstellen', icon: 'logo-google-docs', type: 'process', ...p(0, 2) },
      { id: 'bk7', label: 'Versand an Client', description: 'Per Mail mit PDF-Anhang', icon: 'logo-gmail', type: 'output', ...p(1, 2) },
      { id: 'bk8', label: 'Zahlungseingang prüfen', description: 'Bankabgleich', icon: 'database', type: 'process', ...p(2, 2) },
      { id: 'bk9', label: 'Mahnung versenden', description: 'Bei Zahlungsverzug', icon: 'logo-gmail', type: 'output', ...p(3, 2) },
      { id: 'bk10', label: 'Monatsabschluss', description: 'BWA & Summary generieren', icon: 'logo-google-sheets', type: 'output', ...p(4, 2) },
    ],
    connections: [
      { from: 'bk1', to: 'bk2' },
      { from: 'bk2', to: 'bk3' },
      { from: 'bk3', to: 'bk4' },
      { from: 'bk4', to: 'bk5' },
      { from: 'bk6', to: 'bk7' },
      { from: 'bk7', to: 'bk8' },
      { from: 'bk8', to: 'bk9' },
      { from: 'bk8', to: 'bk10' },
    ],
    groups: [
      { id: 'tbg1', label: 'Eingangsrechnungen', x: 15, y: 8, width: 1380, height: 148, color: 'blue' },
      { id: 'tbg2', label: 'Ausgangsrechnungen & Mahnwesen', x: 15, y: 196, width: 1380, height: 148, color: 'green' },
    ],
  },

  // ── 7. Coach Inbox Copilot ─────────────────────────────────────────────────
  {
    id: 'tpl-coach-inbox',
    user_id: 'local-user',
    name: 'Coach Inbox Copilot',
    description: 'Eingehende E-Mails klassifizieren, FAQ automatisch beantworten, individuelle Antworten vorbereiten und Reminder setzen.',
    category: 'Support',
    icon: 'headphones',
    nodeCount: 9,
    tags: ['coaching', 'inbox', 'email', 'KI-Assistent'],
    nodes: [
      { id: 'ci1', label: 'E-Mail Eingang', description: 'Neue Nachricht empfangen', icon: 'logo-gmail', type: 'trigger', ...p(0, 0) },
      { id: 'ci2', label: 'KI-Klassifizierung', description: 'Kategorie & Dringlichkeit erkennen', icon: 'logo-openai', type: 'ai', ...p(1, 0) },
      { id: 'ci3', label: 'FAQ oder Individuell?', description: 'Routing-Entscheidung', icon: 'git-branch', type: 'process', ...p(2, 0) },
      { id: 'ci4', label: 'FAQ-Antwort', description: 'Standard-Antwort aus Wissensbasis', icon: 'logo-openai', type: 'ai', ...p(3, 0) },
      { id: 'ci5', label: 'Individuelle Antwort', description: 'KI-Draft mit Coach-Review', icon: 'logo-claude', type: 'ai', ...p(3, 1) },
      { id: 'ci6', label: 'Freigabe', description: 'Coach prüft und bestätigt', icon: 'shield-check', type: 'process', ...p(4, 0) },
      { id: 'ci7', label: 'Antwort senden', description: 'E-Mail versenden', icon: 'logo-gmail', type: 'output', ...p(5, 0) },
      { id: 'ci8', label: 'CRM Update', description: 'Interaktion dokumentieren', icon: 'logo-hubspot', type: 'output', ...p(5, 1) },
      { id: 'ci9', label: 'Reminder setzen', description: 'Follow-up in X Tagen', icon: 'clock', type: 'output', ...p(6, 0) },
    ],
    connections: [
      { from: 'ci1', to: 'ci2' },
      { from: 'ci2', to: 'ci3' },
      { from: 'ci3', to: 'ci4' }, { from: 'ci3', to: 'ci5' },
      { from: 'ci4', to: 'ci6' }, { from: 'ci5', to: 'ci6' },
      { from: 'ci6', to: 'ci7' }, { from: 'ci6', to: 'ci8' },
      { from: 'ci7', to: 'ci9' },
    ],
    groups: [
      { id: 'tcg1', label: 'Erfassung & Klassifizierung', x: 15, y: 8, width: 620, height: 148, color: 'purple' },
      { id: 'tcg2', label: 'Antwort-Generierung', x: 695, y: 8, width: 620, height: 256, color: 'blue' },
      { id: 'tcg3', label: 'Versand & Follow-up', x: 1375, y: 8, width: 620, height: 256, color: 'green' },
    ],
  },
]
