import type { ContentItem, ContentFile, ContentPlan } from './types'

export const DEMO_CONTENT: ContentItem[] = [
  {
    id: 'content-1',
    user_id: 'local-user',
    platform: 'youtube',
    title: 'Wie KI dein Marketing revolutioniert',
    concept: 'Schritt-für-Schritt Guide für KI-Tools im Marketing. Fokus auf Automatisierung von repetitiven Aufgaben.',
    angle: 'Die 3 größten Fehler die 90% der Agenturen machen',
    status: 'draft',
    priority: 'high',
    quality: 'neutral',
    tags: ['KI', 'Marketing', 'Automatisierung'],
    notes: 'B-Roll von Tool-Demos einplanen',
    checklist: [
      { id: 'cl-1', text: 'Skript schreiben', completed: true },
      { id: 'cl-2', text: 'Thumbnail erstellen', completed: false },
      { id: 'cl-3', text: 'SEO Keywords recherchieren', completed: true },
      { id: 'cl-4', text: 'Video aufnehmen', completed: false },
    ],
    media: [],
    versions: [],
    videoTitle: 'KI Marketing Guide 2026 — So nutzt du AI richtig',
    videoDescription: 'In diesem Video zeige ich dir...',
    keywords: ['KI Marketing', 'AI Automatisierung', 'Marketing Tools 2026'],
    youtubeCategory: 'Education',
    targetAudience: 'Marketing-Agenturen, Freelancer',
    createdAt: '2026-02-10T08:00:00Z',
    updatedAt: '2026-02-13T14:00:00Z',
  },
  {
    id: 'content-2',
    user_id: 'local-user',
    platform: 'instagram',
    title: '5 KI-Tools die jeder Marketer braucht',
    concept: 'Carousel mit je einem Tool pro Slide. Clean Design, Tool-Screenshots.',
    angle: 'Die Tools die Top-Agenturen nutzen',
    status: 'ready',
    priority: 'medium',
    quality: 'good',
    tags: ['KI', 'Tools', 'Carousel'],
    notes: '',
    checklist: [
      { id: 'cl-1', text: 'Design erstellen', completed: true },
      { id: 'cl-2', text: 'Copy schreiben', completed: true },
      { id: 'cl-3', text: 'Hashtags recherchieren', completed: true },
    ],
    media: [],
    versions: [],
    postType: 'carousel',
    caption: '5 KI-Tools die dein Marketing auf das nächste Level bringen 🚀\n\nWelches Tool nutzt du am meisten? Schreib es in die Kommentare! 👇',
    hashtags: ['KI', 'MarketingTools', 'AIMarketing', 'Automatisierung', 'DigitalMarketing'],
    createdAt: '2026-02-08T10:00:00Z',
    updatedAt: '2026-02-12T16:00:00Z',
  },
  {
    id: 'content-3',
    user_id: 'local-user',
    platform: 'facebook-linkedin',
    title: 'Case Study: 300% mehr Leads durch Automatisierung',
    concept: 'Ergebnis-Post mit konkreten Zahlen. Storytelling-Ansatz.',
    angle: 'Von 10 auf 40 qualifizierte Leads pro Monat',
    status: 'scheduled',
    priority: 'high',
    quality: 'good',
    tags: ['CaseStudy', 'Leads', 'Automatisierung'],
    notes: 'Am Dienstag veröffentlichen',
    scheduledDate: '2026-02-18T09:00:00Z',
    checklist: [
      { id: 'cl-1', text: 'Text schreiben', completed: true },
      { id: 'cl-2', text: 'Grafik erstellen', completed: true },
    ],
    media: [],
    versions: [],
    fbPostType: 'text-image',
    fbCaption: '300% mehr qualifizierte Leads in 3 Monaten.\n\nKein Zufall, sondern System.\n\nSo haben wir es gemacht:',
    fbHashtags: ['CaseStudy', 'LeadGeneration', 'MarketingAutomation'],
    createdAt: '2026-02-05T09:00:00Z',
    updatedAt: '2026-02-14T11:00:00Z',
  },
  {
    id: 'content-4',
    user_id: 'local-user',
    platform: 'youtube',
    title: 'Google Ads Masterclass für Agenturen',
    concept: 'Detaillierter Walkthrough einer erfolgreichen Google Ads Kampagne.',
    angle: 'Wie wir mit 500€ Budget 50 Leads generiert haben',
    status: 'idea',
    priority: 'medium',
    quality: 'neutral',
    tags: ['GoogleAds', 'Tutorial', 'Leads'],
    notes: 'Eventuell als Serie aufbauen',
    checklist: [],
    media: [],
    versions: [],
    createdAt: '2026-02-12T15:00:00Z',
    updatedAt: '2026-02-12T15:00:00Z',
  },
  {
    id: 'content-5',
    user_id: 'local-user',
    platform: 'instagram',
    title: 'Behind the Scenes: Unser Workflow',
    concept: 'Reel mit schnellen Cuts: Tool-Wechsel, Team-Meetings, Ergebnisse.',
    angle: 'So sieht ein Tag bei einer KI-Agentur aus',
    status: 'idea',
    priority: 'low',
    quality: 'neutral',
    tags: ['BTS', 'Agentur', 'Reel'],
    notes: '',
    checklist: [],
    media: [],
    versions: [],
    postType: 'reel',
    createdAt: '2026-02-13T08:00:00Z',
    updatedAt: '2026-02-13T08:00:00Z',
  },
  {
    id: 'content-6',
    user_id: 'local-user',
    platform: 'facebook-linkedin',
    title: 'Warum 80% der KI-Projekte scheitern',
    concept: 'Kontroverse These die Diskussion auslöst. Dann konkrete Lösung liefern.',
    angle: 'Es liegt nicht an der Technologie',
    status: 'live',
    priority: 'high',
    quality: 'good',
    tags: ['KI', 'Kontrovers', 'Strategie'],
    notes: 'Kommentare monitoren',
    checklist: [
      { id: 'cl-1', text: 'Text schreiben', completed: true },
      { id: 'cl-2', text: 'Veröffentlichen', completed: true },
      { id: 'cl-3', text: 'Kommentare beantworten', completed: false },
    ],
    media: [],
    versions: [],
    fbPostType: 'text',
    fbCaption: '80% aller KI-Projekte scheitern.\n\nAber nicht wegen der Technologie.\n\nSondern wegen fehlender Prozesse...',
    createdAt: '2026-01-28T10:00:00Z',
    updatedAt: '2026-02-10T18:00:00Z',
  },
]

export const DEMO_FILES: ContentFile[] = [
  {
    id: 'file-1',
    user_id: 'local-user',
    name: 'Brand Guidelines 2026',
    description: 'Aktuelle Markenrichtlinien inkl. Farben, Fonts, Logo-Verwendung',
    url: '',
    category: 'marketing',
    labels: ['Brand', 'Design'],
    createdAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'file-2',
    user_id: 'local-user',
    name: 'Content Kalender Q1',
    description: 'Übersicht aller geplanten Inhalte für Q1 2026',
    url: '',
    category: 'content',
    labels: ['Planung', 'Q1'],
    createdAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'file-3',
    user_id: 'local-user',
    name: 'Keyword Research — YouTube',
    description: 'Top Keywords für unseren YouTube-Kanal',
    url: '',
    category: 'content',
    labels: ['SEO', 'YouTube'],
    createdAt: '2026-02-01T14:00:00Z',
  },
]

export const DEMO_PLANS: ContentPlan[] = [
  {
    id: 'plan-1',
    user_id: 'local-user',
    name: 'Q1 Content Strategie',
    description: 'Strategischer Content-Plan für das erste Quartal 2026',
    strategy: 'Fokus auf Educational Content + Case Studies. 3x YouTube/Monat, 5x Instagram/Woche, 3x LinkedIn/Woche.',
    deadline: '2026-03-31',
    notes: 'Budget: 2.000€/Monat für Production',
    goal: '1.000 Newsletter-Subscriber bis Ende Q1',
    targetAudience: 'Marketing-Leiter in KMUs, 30-50 Jahre',
    channels: ['YouTube', 'Instagram', 'LinkedIn'],
    tasks: [
      { id: 't-1', title: 'Content-Kalender erstellen', description: 'Alle Themen für Q1 planen', status: 'done', priority: 'high' },
      { id: 't-2', title: 'YouTube Thumbnail-Vorlagen', description: 'Templates für konsistentes Branding', status: 'in-progress', priority: 'medium' },
      { id: 't-3', title: 'Instagram Reels Script Library', description: 'Vorlagen für verschiedene Reel-Formate', status: 'todo', priority: 'medium', dependsOn: ['t-1'] },
      { id: 't-4', title: 'LinkedIn Thought Leadership Posts', description: '12 Posts vorbereiten', status: 'todo', priority: 'high', dependsOn: ['t-1'] },
      { id: 't-5', title: 'KPI Dashboard Setup', description: 'Tracking für alle Kanäle einrichten', status: 'todo', priority: 'low' },
    ],
    createdAt: '2026-01-05T08:00:00Z',
    updatedAt: '2026-02-10T12:00:00Z',
  },
]
